import type { GuidePage } from '../types/content';

export const ghsBasicsPage: GuidePage = {
  id: 'ghs-basics',
  chapter: 19,
  title: 'GHS Basics',
  category: 'ghs-sds',
  summary: 'GHS is the globally harmonized chemical hazard communication system OSHA uses through HazCom for workplace labels and Safety Data Sheets. It is related to DOT hazmat, but it is not the same system.',
  content: [
    { id: 'ghs-basics-p1', type: 'summary', title: 'What GHS means', text: 'GHS means Globally Harmonized System of Classification and Labeling of Chemicals. OSHA describes it as an international approach to chemical hazard communication, including criteria for classifying hazards and standardized label and Safety Data Sheet information.' },
    { id: 'ghs-basics-p2', type: 'warning', title: 'GHS is not the same as DOT hazmat placarding', text: 'GHS/HazCom labels are workplace chemical hazard communication tools. DOT labels, markings, placards, shipping papers, and identification-number displays are transportation hazmat tools under the Hazardous Materials Regulations. Do not use a GHS pictogram alone to decide placards.' },
    { id: 'ghs-basics-p3', type: 'paragraph', text: 'OSHA’s Hazard Communication Standard requires chemical manufacturers and importers to evaluate chemical hazards and communicate hazard information through labels and Safety Data Sheets. Employers with hazardous chemicals in the workplace must make hazard information available and understandable to exposed workers.' },
    { id: 'ghs-basics-p4', type: 'paragraph', text: 'A shipped-container HazCom label normally includes a product identifier, signal word, hazard statement or statements, pictogram or pictograms when required, precautionary statement or statements, and supplier identification. These elements help workers quickly recognize chemical hazards.' },
    { id: 'ghs-basics-p5', type: 'paragraph', text: 'The signal word communicates relative hazard severity. Under OSHA HazCom, the main signal words are Danger and Warning. Danger is used for more severe hazards, and when Danger is required, Warning should not appear for that same label element set.' },
    { id: 'ghs-basics-p6', type: 'paragraph', text: 'Hazard statements describe the nature of the chemical hazard, such as flammability, toxicity, corrosion, or health effects. Precautionary statements describe recommended measures to prevent or reduce harmful effects from exposure, improper handling, or improper storage.' },
    { id: 'ghs-basics-p7', type: 'paragraph', text: 'GHS-style pictograms are red diamond symbols with a black hazard symbol on a white background. OSHA requires eight of the GHS pictograms in the Hazard Communication Standard; the environmental pictogram exists in GHS but is not mandatory under OSHA because environmental hazards are outside OSHA’s jurisdiction.' },
    { id: 'ghs-basics-p8', type: 'paragraph', text: 'Safety Data Sheets, or SDSs, give more detailed chemical hazard information than a label. OSHA’s HazCom system uses a standardized 16-section SDS format so workers and responders can find hazard, handling, storage, exposure-control, first-aid, firefighting, spill, and transport-related information more consistently.' },
    { id: 'ghs-basics-p9', type: 'paragraph', text: 'Workplace container labeling can differ from shipped-container labeling. Employers may use workplace labels or alternative systems such as words, pictures, symbols, or combinations that provide required hazard information, as long as the system meets OSHA requirements and workers are trained to understand it.' },
    { id: 'ghs-basics-p10', type: 'paragraph', text: 'NFPA diamonds and HMIS labels are not the same as OSHA/GHS shipped-container labels. They may appear in workplaces as hazard communication tools, but workers must understand the system being used and must not treat those ratings as DOT placards or shipping-paper substitutes.' },
    { id: 'ghs-basics-p11', type: 'paragraph', text: 'GHS and SDS information can support safety decisions, but DOT transportation compliance still requires the correct shipping description, classification, packaging, labels, markings, placards, and shipping papers under the HMR. The SDS may include transport information, but the shipping paper controls the active shipment decision.' },
    { id: 'ghs-basics-p12', type: 'example', title: 'Example: flame pictogram', text: 'A GHS flame pictogram means the chemical has a flammability-related hazard under workplace hazard communication. It does not automatically tell you whether a truck needs Class 3 placards or a UN number display. For transport, check the shipping paper and HMR.' },
    { id: 'ghs-basics-p13', type: 'example', title: 'Example: corrosive symbol', text: 'A GHS corrosion pictogram can warn about skin burns, eye damage, or corrosive effects on metals. That does not automatically replace DOT Class 8 label or placard decisions. Workplace labeling and transport labeling must be checked separately.' },
    { id: 'ghs-basics-p14', type: 'example', title: 'Example: SDS section 14', text: 'An SDS may include transport information in Section 14, but SDS information should be verified against the shipping paper, current classification, package, quantity, and DOT hazmat requirements before a load moves.' },
    { id: 'ghs-basics-p15', type: 'checklist', title: 'Quick GHS check', items: ['Identify the product name or product identifier.', 'Look for signal word: Danger or Warning.', 'Read the hazard statements.', 'Read the precautionary statements.', 'Identify any required pictograms.', 'Open the SDS for more complete information.', 'Confirm workers are trained on the label system used at the site.', 'Do not use GHS labels alone to decide DOT placards or shipping papers.', 'Escalate unclear chemical hazards to a supervisor, safety contact, or SDS owner.'] },
    { id: 'ghs-basics-p16', type: 'warning', title: 'Use the right system for the question', text: 'If the question is workplace chemical safety, start with HazCom labels, SDSs, training, and employer procedures. If the question is transportation compliance, start with the hazmat shipping paper, HMR classification, package, quantity, labels, markings, placards, and identification-number display requirements.' }
  ],
  audioScript: 'GHS basics. GHS means Globally Harmonized System of Classification and Labeling of Chemicals. OSHA uses GHS-style hazard communication through the Hazard Communication Standard. A HazCom label can include a product identifier, signal word, hazard statements, pictograms, precautionary statements, and supplier information. Safety Data Sheets provide more detailed chemical hazard information in a standardized 16-section format. GHS workplace labels and SDSs are not the same as DOT transportation placards, shipping papers, package labels, markings, or identification-number displays. Use the right system for the question: HazCom for workplace chemical safety, and DOT HMR for transportation compliance.',
  tags: ['ghs basics', 'globally harmonized system', 'hazcom', 'osha hazard communication', 'sds', 'safety data sheet', 'signal word', 'hazard statement', 'precautionary statement', 'pictogram', 'workplace label', 'dot vs ghs'],
  sources: [
    { title: 'Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/', note: 'OSHA overview of the Hazard Communication Standard, labels, SDSs, and training.' },
    { title: 'Globally Harmonized System', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/global', note: 'OSHA explanation of GHS as an international approach to classification, labels, and SDSs.' },
    { title: 'Hazard Communication Pictograms', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/pictograms', note: 'OSHA pictogram page explaining red diamond pictogram format and available pictogram files.' },
    { title: 'Hazard Communication Appendix C - Allocation of Label Elements', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/appendix-c', note: 'OSHA mandatory appendix covering label elements, signal words, hazard statements, pictograms, and precautionary statements.' },
    { title: 'Hazard Communication Questions and Answers', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/faq', note: 'OSHA FAQ explaining pictograms, workplace labels, HMIS/NFPA questions, and related HazCom topics.' },
    { title: 'Safety Data Sheets QuickCard', agency: 'OSHA', url: 'https://obis.osha.gov/Publications/HazComm_QuickCard_SafetyData.html', note: 'OSHA quick reference explaining SDS purpose and sections.' },
    { title: '29 CFR 1910.1200 - Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200', note: 'Official OSHA regulatory text for the Hazard Communication Standard.' }
  ],
  lastReviewed: '2026-05-20'
};
