import type { GuidePage } from '../types/content';

export const shippingPapersPage: GuidePage = {
  id: 'shipping-papers',
  chapter: 13,
  title: 'Shipping Papers',
  category: 'hazmat-placards',
  summary: 'Shipping papers are the core hazmat transportation document. They communicate what regulated material is being offered or transported and help drive labels, markings, placards, emergency response information, and inspection decisions.',
  content: [
    { id: 'shipping-papers-p1', type: 'summary', title: 'What shipping papers do', text: 'A hazardous materials shipping paper is a transportation document that describes the regulated hazardous material being offered or transported. It is one of the main ways carriers, drivers, enforcement, and emergency responders identify what is on the vehicle.' },
    { id: 'shipping-papers-p2', type: 'warning', title: 'Do not guess from labels alone', text: 'A package label, placard, SDS, customer paperwork, or driver comment does not replace the required hazmat shipping paper. When a real hazmat decision is being made, start with the shipping paper and verify against the Hazardous Materials Regulations.' },
    { id: 'shipping-papers-p3', type: 'paragraph', text: 'The basic description on a hazmat shipping paper generally includes the identification number, proper shipping name, hazard class or division, and packing group when a packing group is assigned. The required order and additional entries can vary by rule, material, and shipment details.' },
    { id: 'shipping-papers-p4', type: 'paragraph', text: 'The shipping paper may also include required additional information, such as total quantity, number and type of packages, emergency response telephone number, technical name when required, special permits, hazardous substance or marine pollutant information, limited quantity information, or other required notations.' },
    { id: 'shipping-papers-p5', type: 'paragraph', text: 'The person who offers a hazardous material for transportation is generally responsible for properly classifying, describing, packaging, marking, labeling, and preparing the shipment. Drivers and dock workers should not independently invent or change hazmat descriptions unless they are trained, authorized, and following company procedure.' },
    { id: 'shipping-papers-p6', type: 'paragraph', text: 'Carriers and drivers still have responsibilities. The shipping paper must be accessible during transportation, and the driver must be able to produce it when required. In highway transportation, 49 CFR §177.817 contains specific requirements for shipping papers carried in a motor vehicle.' },
    { id: 'shipping-papers-p7', type: 'paragraph', text: 'The shipping paper can help answer whether the shipment is regulated, what hazard class applies, what identification number is involved, and what emergency response information must be available. It does not automatically answer every placarding question by itself; quantity, packaging type, and exceptions still matter.' },
    { id: 'shipping-papers-p8', type: 'paragraph', text: 'Emergency response information must be available for hazardous materials as required by the HMR. PHMSA explains that emergency response information may be on the shipping paper, in another document such as an SDS that includes required identifying information, or in a separate document such as an Emergency Response Guidebook reference that is properly related to the shipping paper.' },
    { id: 'shipping-papers-p9', type: 'paragraph', text: 'Shipping papers must be distinguishable from other paperwork when they include both hazardous and non-hazardous materials. The HMR includes rules for clearly identifying the hazardous material entries so they do not get lost among ordinary freight descriptions.' },
    { id: 'shipping-papers-p10', type: 'paragraph', text: 'Retention matters. PHMSA rulemaking explains that shippers and carriers must retain copies or electronic images of hazmat shipping papers for specified periods. Hazardous waste shipping paper retention can be longer than ordinary hazardous material shipping paper retention.' },
    { id: 'shipping-papers-p11', type: 'paragraph', text: 'Some materials or shipments may be excepted from shipping paper requirements, such as certain limited quantities in certain modes or materials of trade when all conditions are met. Do not assume an exception applies just because a shipment seems small or familiar.' },
    { id: 'shipping-papers-p12', type: 'paragraph', text: 'Shipping papers, SDS documents, bills of lading, manifests, delivery tickets, and ERG pages can overlap in real life, but they are not interchangeable. The key question is whether the document contains the required hazmat transportation description and required information for that shipment.' },
    { id: 'shipping-papers-p13', type: 'example', title: 'Example: Class 3 package', text: 'A package has a Class 3 label. The shipping paper should identify the regulated material with the required hazmat description, including the proper shipping name and identification number. The label alone does not tell you the full shipping description or all placarding requirements.' },
    { id: 'shipping-papers-p14', type: 'example', title: 'Example: ERG information', text: 'A driver has an Emergency Response Guidebook in the cab. That can support emergency response information, but the shipping paper still needs to identify the hazardous material so the correct emergency response information can be matched to the shipment.' },
    { id: 'shipping-papers-p15', type: 'example', title: 'Example: mismatch problem', text: 'If the shipping paper says one UN number, the package marking shows another, and the placard does not match the hazard class, do not guess which one is right. Stop and escalate to a qualified hazmat/safety contact before the shipment moves.' },
    { id: 'shipping-papers-p16', type: 'checklist', title: 'Quick shipping paper check', items: ['Confirm the document is the hazmat shipping paper or contains the required hazmat shipping description.', 'Check the identification number.', 'Check the proper shipping name.', 'Check the hazard class or division.', 'Check the packing group when assigned.', 'Check quantity, number/type of packages, and packaging details.', 'Check emergency response telephone number and emergency response information availability.', 'Check whether the hazmat entries are clearly distinguished from non-hazmat entries.', 'Compare the shipping paper against package markings, labels, and placards for obvious mismatches.', 'Escalate mismatches or missing information to a trained hazmat/safety contact.'] },
    { id: 'shipping-papers-p17', type: 'warning', title: 'If the paper and freight do not match, stop', text: 'Mismatched hazmat descriptions, labels, markings, placards, or emergency information can create serious safety and enforcement problems. Do not “fix” a shipping paper on your own unless you are trained, authorized, and following the applicable regulation and company procedure.' }
  ],
  audioScript: 'Shipping papers. A hazardous materials shipping paper is a transportation document that describes the regulated hazardous material being offered or transported. It helps carriers, drivers, enforcement, and emergency responders identify what is on the vehicle. The basic description generally includes the identification number, proper shipping name, hazard class or division, and packing group when assigned. Additional information can also be required. The offeror is generally responsible for properly classifying and describing the material, but drivers and carriers still have responsibilities to keep the shipping paper accessible and produce it when required. If the shipping paper, package labels, markings, placards, or emergency response information do not match, stop and escalate to a qualified hazmat or safety contact.',
  tags: ['shipping papers', 'hazmat shipping paper', 'basic description', 'proper shipping name', 'identification number', 'un number', 'na number', 'hazard class', 'packing group', 'emergency response information', 'bill of lading', 'manifest', '177.817', '172.202', '172.200'],
  sources: [
    { title: '49 CFR Part 172 Subpart C - Shipping Papers', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172/subpart-C', note: 'Official eCFR regulatory text for hazmat shipping paper requirements.' },
    { title: '49 CFR Section 172.202 - Description of hazardous material on shipping papers', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/172202', note: 'PHMSA regulatory text page for hazardous material descriptions on shipping papers.' },
    { title: '49 CFR Section 177.817 - Shipping papers', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/177817', note: 'PHMSA regulatory text page for highway transportation shipping paper requirements.' },
    { title: 'Hazardous Materials: Emergency Response Information Requirements', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulatory-compliance/phmsa-guidance/hazardous-materials-emergency-response-information', note: 'PHMSA guidance explaining emergency response information and how it may relate to shipping papers.' },
    { title: 'Hazmat Transportation Requirements PDF', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/hazmat-transportation-requirements-pdf', note: 'PHMSA training brochure covering preparing shipping papers and using the Hazardous Materials Table.' },
    { title: 'Hazardous Materials: Retention of Shipping Papers', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/federal-register-documents/02-17566', note: 'PHMSA Federal Register document discussing shipping paper retention requirements.' },
    { title: '49 CFR Part 172 - Hazardous Materials Table, Special Provisions, Communications, Emergency Response Information, Training Requirements, and Security Plans', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172', note: 'Official eCFR regulatory text for Part 172 communication and shipping paper requirements.' }
  ],
  lastReviewed: '2026-05-20'
};
