import type { GuidePage } from '../types/content';

export const checklistsPage: GuidePage = {
  id: 'checklists',
  chapter: 23,
  title: 'Checklists',
  category: 'checklists',
  summary: 'Practical, non-certifying checklists for HOS, ELD, hazmat shipping papers, placards, bulk packaging, GHS labels, and SDS review. These checklists guide users to verify; they do not replace official rules or company procedures.',
  content: [
    { id: 'checklists-p1', type: 'summary', title: 'How to use these checklists', text: 'Use these checklists as a quick way to slow down, organize the question, and catch obvious problems. They are not a legal determination, not hazmat training, not an ELD, and not a substitute for the FMCSA, PHMSA, OSHA, eCFR, or company safety procedure.' },
    { id: 'checklists-p2', type: 'warning', title: 'A checked box is not compliance by itself', text: 'Checking every item in this app does not prove a driver, carrier, shipper, employer, or hazmat employee is compliant. The official rule, the actual shipment, the actual log, and trained company review still control.' },
    { id: 'checklists-p3', type: 'checklist', title: 'HOS quick check', items: ['Confirm the operation is property-carrying or passenger-carrying.', 'Check the driver has the required off-duty reset before the duty period.', 'Check the applicable driving limit.', 'Check the applicable duty window.', 'Check the 30-minute break rule when applicable.', 'Check the 60/70-hour cycle.', 'Check sleeper berth only if the driver is actually using a valid split.', 'Check exceptions only when every condition is met.', 'Use the actual log or ELD, not memory.'] },
    { id: 'checklists-p4', type: 'checklist', title: 'ELD quick check', items: ['Confirm the driver is required to use an ELD for this operation.', 'Confirm the driver is logged in before driving.', 'Confirm duty status choices are correct.', 'Review unidentified driving records.', 'Know how to display or transfer records during inspection.', 'Keep required ELD documents and backup graph-grids available.', 'Follow malfunction procedures if the device fails.', 'Do not treat the ELD as permission to violate HOS rules.'] },
    { id: 'checklists-p5', type: 'checklist', title: 'Hazmat shipping paper check', items: ['Confirm the document is the hazmat shipping paper or contains the required hazmat shipping description.', 'Check the identification number.', 'Check the proper shipping name.', 'Check the hazard class or division.', 'Check the packing group when assigned.', 'Check quantity, number/type of packages, and packaging details.', 'Check emergency response telephone number and emergency response information.', 'Check whether hazmat entries are clearly distinguished from non-hazmat entries.', 'Compare the paperwork against package markings, labels, and placards.', 'Escalate mismatches or missing information.'] },
    { id: 'checklists-p6', type: 'checklist', title: 'Placard decision check', items: ['Start with the shipping paper.', 'Confirm proper shipping name, identification number, hazard class/division, and packing group when assigned.', 'Check the Hazardous Materials Table and special provisions.', 'Determine whether Table 1 or Table 2 placarding logic applies.', 'Check total quantity and aggregate gross weight when relevant.', 'Determine bulk versus non-bulk packaging.', 'Check whether placards are required.', 'Check whether an identification-number display is required.', 'Check whether an exception or special case truly applies.', 'Compare final displays against shipping papers, package markings, and labels.', 'Pause and escalate uncertainty before the shipment moves.'] },
    { id: 'checklists-p7', type: 'checklist', title: 'Bulk versus non-bulk check', items: ['Start with the shipping paper and package information.', 'Identify whether the material is liquid, solid, or gas.', 'Check package capacity or net mass against bulk packaging thresholds.', 'Confirm whether the material is loaded with no intermediate form of containment.', 'Check proper shipping name, hazard class/division, identification number, and packing group when assigned.', 'Check bulk package marking requirements.', 'Check placard and identification-number-display requirements.', 'Check residue, empty-package, closure, and company procedure requirements.', 'Escalate unclear capacity or packaging questions.'] },
    { id: 'checklists-p8', type: 'checklist', title: 'Dock dispute check', items: ['Stop the argument and name the exact question.', 'Start with the shipping paper, not memory or habit.', 'Confirm labels and markings against the paperwork.', 'Check bulk versus non-bulk packaging.', 'Check placarding and identification-number display rules.', 'Check whether any exception truly applies.', 'Do not rely on SDS/GHS as DOT placarding authority.', 'Do not release a mismatch by pressure.', 'Escalate to a trained hazmat/safety contact.', 'Document the issue if company procedure requires it.'] },
    { id: 'checklists-p9', type: 'checklist', title: 'GHS label check', items: ['Identify the product identifier.', 'Look for the signal word: Danger or Warning.', 'Read the hazard statements.', 'Read the precautionary statements.', 'Identify every pictogram.', 'Find supplier information.', 'Open the SDS for complete details.', 'Confirm workers understand the label system used at the site.', 'Do not use a GHS label alone to decide DOT placards.'] },
    { id: 'checklists-p10', type: 'checklist', title: 'SDS quick check', items: ['Confirm the product identifier matches the container.', 'Check Section 2 for hazards, signal word, pictograms, and hazard statements.', 'Check Section 4 for first aid.', 'Check Section 5 for firefighting information.', 'Check Section 6 for spill response.', 'Check Section 7 for handling and storage.', 'Check Section 8 for exposure controls and PPE.', 'Check Section 14 only as transport support, not as a replacement for shipping papers.', 'Check Section 16 for revision date.', 'Escalate missing, outdated, or conflicting SDS information.'] },
    { id: 'checklists-p11', type: 'paragraph', text: 'These checklists intentionally repeat key safety themes from earlier chapters. Repetition is useful because the most common mistakes happen when users jump directly to an answer without checking the document, rule, quantity, packaging, or actual log.' },
    { id: 'checklists-p12', type: 'paragraph', text: 'For HOS questions, the actual ELD or log record matters. For hazmat transportation questions, the actual shipping paper and shipment configuration matter. For GHS/SDS workplace questions, the actual container label, SDS, training, and site procedure matter.' },
    { id: 'checklists-p13', type: 'warning', title: 'When any checklist finds a mismatch', text: 'A mismatch is not something to “work around.” If the paperwork, labels, markings, placards, SDS, ELD, log, or company instructions conflict, stop and verify through a qualified supervisor, safety contact, carrier contact, or official source.' }
  ],
  audioScript: 'Checklists. These checklists are quick guides to slow down and organize common driver, dock, hazmat, GHS, SDS, and HOS questions. They do not replace official rules, company procedures, hazmat training, an ELD, or qualified safety review. For HOS, use the actual log or ELD. For hazmat, start with the shipping paper and shipment details. For GHS and SDS questions, use the label, Safety Data Sheet, training, and employer procedure. A checked box is not compliance by itself. If documents, labels, placards, markings, SDS information, ELD records, or instructions do not match, pause and escalate before acting.',
  tags: ['checklists', 'hos checklist', 'eld checklist', 'hazmat checklist', 'shipping paper checklist', 'placard checklist', 'bulk checklist', 'dock dispute checklist', 'ghs checklist', 'sds checklist'],
  sources: [
    { title: 'Summary of Hours of Service Regulations', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/summary-hours-service-regulations', note: 'FMCSA summary used for HOS checklist topics.' },
    { title: 'Electronic Logging Devices', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/electronic-logging-devices', note: 'FMCSA ELD overview used for ELD checklist topics.' },
    { title: '49 CFR Part 172 - Hazardous Materials Table, Special Provisions, Communications, Emergency Response Information, Training Requirements, and Security Plans', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172', note: 'Official eCFR hazmat communication rules used for hazmat checklist topics.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' },
    { title: 'Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/', note: 'OSHA overview used for GHS label and SDS checklist topics.' },
    { title: 'Safety Data Sheets QuickCard', agency: 'OSHA', url: 'https://obis.osha.gov/Publications/HazComm_QuickCard_SafetyData.html', note: 'OSHA quick reference used for SDS checklist topics.' }
  ],
  lastReviewed: '2026-05-20'
};
