import type { GuidePage } from '../types/content';

export const numberedPlacardsPage: GuidePage = {
  id: 'numbered-placards',
  chapter: 15,
  title: 'Numbered Placards',
  category: 'hazmat-placards',
  summary: 'Numbered placards and other identification-number displays show the four-digit UN or NA number for a hazardous material, but they are not required or allowed in every placarding situation.',
  content: [
    { id: 'numbered-placards-p1', type: 'summary', title: 'What a numbered placard means', text: 'A numbered placard is a hazard placard that also displays the four-digit hazardous material identification number. The number helps identify the specific material or group of materials involved, but it does not replace the shipping paper, package markings, or the rest of the HMR.' },
    { id: 'numbered-placards-p2', type: 'warning', title: 'A plain class placard is not always enough', text: 'A driver may ask for a plain Class 3, Class 8, or other hazard class placard because that is what they are used to. That can be wrong when the rules require an identification number display. Always check the shipping paper, packaging type, quantity, and current HMR before deciding.' },
    { id: 'numbered-placards-p3', type: 'paragraph', text: 'Identification numbers are usually UN or NA four-digit numbers. They can appear on shipping papers, package markings, bulk package markings, orange panels, white square-on-point displays, or placards depending on the material and the rule.' },
    { id: 'numbered-placards-p4', type: 'paragraph', text: 'The identification number display is not always physically on the placard. The HMR allows identification numbers to be displayed in different ways, including on an orange panel, on the proper placard, or in a white square-on-point display when allowed by the rule.' },
    { id: 'numbered-placards-p5', type: 'paragraph', text: 'Bulk packaging is one of the biggest reasons numbered displays matter. Bulk packages often require the hazardous material identification number to be displayed. Cargo tanks, portable tanks, tank cars, and other bulk packages can have marking and placarding requirements that are not the same as small non-bulk packages.' },
    { id: 'numbered-placards-p6', type: 'paragraph', text: 'A placard with an identification number must match the material and hazard class requirements. PHMSA interpretation guidance has warned that an identification number on a placard may not be used to satisfy placarding requirements unless it is the correct identification number for the hazardous material of that class in the transport vehicle or freight container.' },
    { id: 'numbered-placards-p7', type: 'paragraph', text: 'A numbered display can create confusion when more than one hazardous material of the same hazard class is loaded. Do not put one material’s identification number on a placard if that would misidentify other materials of the same class or conflict with the HMR.' },
    { id: 'numbered-placards-p8', type: 'paragraph', text: 'Some shipments may be placarded by hazard class without an identification number display. Some may require an identification number display. Some may qualify for an exception. The answer depends on the material, quantity, packaging, shipment configuration, and specific section of the HMR.' },
    { id: 'numbered-placards-p9', type: 'paragraph', text: 'Orange panels and white square-on-point displays are not decoration. They are regulated ways to display identification numbers when allowed or required. Their format, visibility, and placement must follow the applicable HMR requirements.' },
    { id: 'numbered-placards-p10', type: 'paragraph', text: 'The shipping paper is the starting point. Compare the identification number on the shipping paper with the package marking, bulk package marking, placard, orange panel, or white square-on-point display. If they do not line up, stop and escalate.' },
    { id: 'numbered-placards-p11', type: 'paragraph', text: 'Emergency responders use identification numbers along with placard colors, symbols, hazard classes, shipping papers, and emergency response information to understand hazards. A wrong number can point people toward the wrong material and the wrong response information.' },
    { id: 'numbered-placards-p12', type: 'paragraph', text: 'GHS pictograms and SDS information do not answer whether a DOT identification number display is required. DOT transportation identification-number displays come from the Hazardous Materials Regulations.' },
    { id: 'numbered-placards-p13', type: 'example', title: 'Example: driver asks for plain Class 3 placards', text: 'A driver hauling a bulk flammable liquid asks for plain red Class 3 placards and says a numbered placard is not needed. That may be wrong. Bulk packaging and identification-number-display rules must be checked before deciding.' },
    { id: 'numbered-placards-p14', type: 'example', title: 'Example: orange panel instead of numbered placard', text: 'A cargo tank may display the identification number on an orange panel or in another allowed configuration rather than directly inside the placard, depending on the rule and shipment. The key is that the required identification number display is correct and properly placed.' },
    { id: 'numbered-placards-p15', type: 'example', title: 'Example: wrong number is worse than no guess', text: 'If the shipping paper shows UN1203 and the placard or panel shows a different number, do not assume either one is correct. A mismatched identification number can mislead emergency responders and enforcement. Escalate before the shipment moves.' },
    { id: 'numbered-placards-p16', type: 'checklist', title: 'Quick numbered placard check', items: ['Start with the shipping paper and the Hazardous Materials Table entry.', 'Confirm the UN or NA identification number.', 'Confirm the hazard class or division.', 'Confirm whether the shipment is bulk or non-bulk.', 'Check whether an identification number display is required.', 'Check whether the number may appear on a placard, orange panel, or white square-on-point display.', 'Confirm the displayed number matches the material and does not misidentify other materials.', 'Compare the number against package markings and bulk package markings.', 'Check visibility, placement, and condition.', 'Escalate mismatches or uncertainty to a trained hazmat/safety contact.'] },
    { id: 'numbered-placards-p17', type: 'warning', title: 'Do not let habit overrule the shipment', text: 'The correct answer is not “we always use plain placards” or “the driver’s app says it is fine.” The correct answer comes from the shipping paper, packaging, quantity, and current HMR.' }
  ],
  audioScript: 'Numbered placards. A numbered placard is a hazard placard that also displays the four-digit hazardous material identification number, such as a UN or NA number. Identification numbers may also appear on orange panels or white square-on-point displays when allowed or required. Bulk packaging is one of the biggest reasons numbered displays matter. A plain hazard class placard is not always enough, and a wrong number can mislead emergency responders. Start with the shipping paper, confirm the identification number, check whether the shipment is bulk or non-bulk, and verify whether the number must be displayed on a placard, orange panel, or white square-on-point display. If the numbers, placards, markings, or shipping papers do not match, stop and escalate.',
  tags: ['numbered placards', 'identification number', 'un number', 'na number', 'orange panel', 'white square on point', 'bulk package', 'cargo tank', 'placard', 'class 3 placard', 'hazmat', 'phmsa', '172.332', '172.334', '172.336'],
  sources: [
    { title: '49 CFR Section 172.503 - Identification number display on placards', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/172503', note: 'PHMSA regulatory text page for identification number display on placards.' },
    { title: '49 CFR Section 172.332 - Identification number markings', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.332', note: 'Official eCFR text for identification number markings.' },
    { title: '49 CFR Section 172.334 - Identification numbers; prohibited display', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.334', note: 'Official eCFR text covering prohibited identification number display.' },
    { title: '49 CFR Section 172.336 - Identification numbers; special provisions', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.336', note: 'Official eCFR text for special provisions related to identification numbers.' },
    { title: 'Identifying Hazardous Materials in Your Community', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/standards-rulemaking/hazmat/identifying-hazardous-materials-in-your-community', note: 'PHMSA explanation of placards, colors, symbols, and identification numbers.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' },
    { title: 'Interpretation Response #16-0026', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/interp/16-0026', note: 'PHMSA interpretation discussing identification numbers on placards and correct matching to hazardous materials.' }
  ],
  lastReviewed: '2026-05-20'
};
