import type { GuidePage } from '../types/content';

export const sourcesUpdatesPage: GuidePage = {
  id: 'sources-updates',
  chapter: 26,
  title: 'Sources / Last Updated / Change Log',
  category: 'sources',
  summary: 'A plain-English source and update page explaining which official agencies this app relies on, how users should verify current rules, and how content changes should be tracked.',
  content: [
    { id: 'sources-updates-p1', type: 'summary', title: 'Why this page exists', text: 'Driver Rulebook is built around official source verification. This page explains where the app’s rule explanations come from, how users should verify them, and why a last-reviewed date matters.' },
    { id: 'sources-updates-p2', type: 'warning', title: 'The source controls, not the app', text: 'This app is a plain-English guide. It does not replace current federal regulations, official agency guidance, shipping papers, SDS documents, ELD records, employer procedures, legal advice, or trained safety personnel. When there is a conflict, verify with the official source and qualified company process.' },
    { id: 'sources-updates-p3', type: 'paragraph', text: 'FMCSA is the main federal source used for hours-of-service and ELD topics in this app. FMCSA materials are used for property-carrying HOS summaries, passenger-carrying cautions, short-haul concepts, adverse driving conditions, sleeper berth guidance, cycle limits, ELD basics, ELD documentation, and ELD malfunction topics.' },
    { id: 'sources-updates-p4', type: 'paragraph', text: 'PHMSA is the main federal source used for hazardous materials transportation topics in this app. PHMSA materials and 49 CFR hazmat rules are used for hazmat basics, shipping papers, labels, markings, placards, identification numbers, bulk packaging, emergency response information, training, and hazardous materials communication.' },
    { id: 'sources-updates-p5', type: 'paragraph', text: 'OSHA is the main federal source used for workplace chemical hazard communication topics in this app. OSHA materials are used for GHS/HazCom labels, pictograms, signal words, hazard statements, precautionary statements, Safety Data Sheets, SDS accessibility, and workplace chemical safety communication.' },
    { id: 'sources-updates-p6', type: 'paragraph', text: 'The eCFR is used for official federal regulatory text. For this app, important eCFR areas include 49 CFR Part 395 for hours of service, 49 CFR Parts 171 through 180 for hazardous materials transportation, and 29 CFR §1910.1200 for OSHA Hazard Communication.' },
    { id: 'sources-updates-p7', type: 'paragraph', text: 'Source links inside each chapter are meant to point users toward official verification. They should not be treated as decoration. A real compliance decision should be checked against the current source, the actual shipment or log, and company procedure.' },
    { id: 'sources-updates-p8', type: 'paragraph', text: 'Each researched page includes a last-reviewed date. That date means the app content was reviewed against the listed sources on that date. It does not guarantee that the rule has not changed after that date.' },
    { id: 'sources-updates-p9', type: 'paragraph', text: 'A page should be re-reviewed when a federal rule changes, an agency publishes updated guidance, a source link breaks, a company procedure changes, or users report that content appears unclear, incomplete, outdated, or potentially wrong.' },
    { id: 'sources-updates-p10', type: 'paragraph', text: 'For HOS and ELD topics, users should verify the actual driver record, the operation type, property versus passenger rules, applicable exceptions, interstate or intrastate status, employer policy, and current FMCSA guidance before acting.' },
    { id: 'sources-updates-p11', type: 'paragraph', text: 'For hazmat transportation topics, users should verify the actual shipping paper, proper shipping name, identification number, hazard class or division, packing group when assigned, quantity, packaging type, placarding table, identification-number display requirements, exceptions, and current PHMSA/eCFR rules before a shipment moves.' },
    { id: 'sources-updates-p12', type: 'paragraph', text: 'For GHS and SDS topics, users should verify the actual container label, SDS, product identifier, revision date, employer training, PPE requirements, storage instructions, spill response, first aid information, and OSHA HazCom requirements before handling chemicals.' },
    { id: 'sources-updates-p13', type: 'paragraph', text: 'This app intentionally repeats warnings across chapters because many real mistakes happen when users skip the source document and rely on habit. Repetition is a safety feature, not filler.' },
    { id: 'sources-updates-p14', type: 'example', title: 'Example: source conflict', text: 'A driver app says plain Class 3 placards are fine, but the shipping paper and bulk package information suggest an identification-number display may be required. The app shown by the driver does not control the shipment. Verify the shipping paper, current HMR, and trained company safety process.' },
    { id: 'sources-updates-p15', type: 'example', title: 'Example: outdated memory', text: 'A worker remembers an old chemical label or an old SDS. The product identifier, supplier, formulation, or revision date may have changed. Verify against the current SDS and employer system before relying on it.' },
    { id: 'sources-updates-p16', type: 'example', title: 'Example: HOS source check', text: 'A driver believes a break reset the day. The official HOS source and the actual ELD/log should be checked. A normal 30-minute break does not restart the 14-hour window, the 11-hour driving limit, or the 60/70-hour cycle.' },
    { id: 'sources-updates-p17', type: 'checklist', title: 'Before trusting any page', items: ['Check the page last-reviewed date.', 'Open the official source link for real compliance decisions.', 'Confirm the rule applies to the actual operation or shipment.', 'Use the actual ELD/log, shipping paper, label, SDS, or company procedure.', 'Check whether state, intrastate, employer, customer, or modal rules are stricter.', 'Escalate conflicts or uncertainty to a qualified safety contact.'] },
    { id: 'sources-updates-p18', type: 'checklist', title: 'Content update checklist', items: ['Record what changed and why.', 'Record which chapter or page changed.', 'Verify the change against official sources.', 'Update the last-reviewed date when a page is substantively reviewed.', 'Avoid changing safety meaning without source support.', 'Keep outdated or superseded guidance out of beginner-facing text.', 'Keep source notes clear about guidance versus regulation.'] },
    { id: 'sources-updates-p19', type: 'paragraph', title: 'Current content status', text: 'Chapters 1 through 26 are structured and sourced for a first complete guide pass. Future work should focus on testing app behavior, improving navigation and search, validating source links, proofreading content, and reviewing rules on a regular schedule.' },
    { id: 'sources-updates-p20', type: 'warning', title: 'Final safety rule', text: 'If the app, a driver, a dock worker, a shipping paper, an SDS, a placard, an ELD, or a memory-based answer conflicts with an official source or qualified safety process, stop and verify. Do not guess.' }
  ],
  audioScript: 'Sources, last updated, and change log. Driver Rulebook is built around official source verification. FMCSA is used for hours-of-service and ELD topics. PHMSA and the Hazardous Materials Regulations are used for hazmat transportation topics. OSHA and HazCom are used for GHS labels, pictograms, and Safety Data Sheets. The eCFR is used for official federal regulatory text. A last-reviewed date means the page was reviewed against the listed sources on that date, but rules and guidance can change. For real decisions, check the official source, the actual log or shipping paper or SDS, and company procedure. If anything conflicts, stop and verify.',
  tags: ['sources', 'last updated', 'change log', 'official sources', 'fmcsa', 'phmsa', 'osha', 'ecfr', 'source verification', 'rule updates', 'content review'],
  sources: [
    { title: 'Hours of Service', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-of-service', note: 'Official FMCSA HOS topic page.' },
    { title: 'Electronic Logging Devices', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/electronic-logging-devices', note: 'Official FMCSA ELD overview.' },
    { title: 'Hazardous Materials Regulations', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/standards-rulemaking/hazmat/hazardous-materials-regulations', note: 'PHMSA overview of the Hazardous Materials Regulations.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' },
    { title: 'Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/', note: 'Official OSHA Hazard Communication overview.' },
    { title: '29 CFR 1910.1200 - Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200', note: 'Official OSHA HazCom regulatory text.' },
    { title: 'eCFR Title 49', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49', note: 'Official eCFR Title 49 regulatory text.' },
    { title: 'eCFR Title 29', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-29', note: 'Official eCFR Title 29 regulatory text.' }
  ],
  lastReviewed: '2026-05-20'
};
