import type { GuidePage } from '../types/content';

export const resetRestartPage: GuidePage = {
  id: 'reset-restart',
  chapter: 8,
  title: '10-Hour Reset and 34-Hour Restart',
  category: 'hos',
  summary: 'The 10-hour reset restores the daily property-carrying driving window, while the 34-hour restart can restart the 60/70-hour cycle calculation.',
  content: [
    { id: 'reset-restart-p1', type: 'summary', title: 'The short version', text: 'For many property-carrying drivers under federal HOS rules, 10 consecutive hours off duty is the normal reset before a new 11-hour driving limit and 14-hour driving window. A 34-hour restart is different: it can restart the 60/70-hour cycle calculation after 34 or more consecutive hours off duty.' },
    { id: 'reset-restart-p2', type: 'warning', title: 'Do not mix these up', text: 'A 10-hour reset and a 34-hour restart solve different problems. A 10-hour reset is about the next daily driving period. A 34-hour restart is about the weekly or cycle limit. Taking 10 hours off does not automatically restart the 60/70-hour cycle.' },
    { id: 'reset-restart-p3', type: 'paragraph', text: 'The 10-hour reset is tied to the property-carrying daily HOS pattern. After 10 consecutive hours off duty, a covered property-carrying driver can generally start a new period with up to 11 hours of driving inside the applicable 14-hour driving window, assuming no other limit or rule blocks driving.' },
    { id: 'reset-restart-p4', type: 'paragraph', text: 'The word consecutive matters. A broken set of off-duty periods does not automatically equal a normal 10-hour reset. If the driver is using ordinary off-duty time to reset the daily clocks, the off-duty period must be continuous unless a specific sleeper berth rule or exception applies.' },
    { id: 'reset-restart-p5', type: 'paragraph', text: 'Sleeper berth rules can allow different ways to obtain the required off-duty time, but those rules are more specific. A driver should not assume that any two rest periods can be added together. Use the sleeper berth chapter before relying on a split sleeper calculation.' },
    { id: 'reset-restart-p6', type: 'paragraph', text: 'The 34-hour restart is connected to the 60/70-hour cycle. FMCSA summarizes the rule by saying a driver may restart a 7- or 8-consecutive-day period after taking 34 or more consecutive hours off duty. This can clear the cycle calculation when used correctly.' },
    { id: 'reset-restart-p7', type: 'paragraph', text: 'A valid 34-hour restart does not erase the need to follow the daily rules after returning to work. After the restart, the driver still must follow the 11-hour driving limit, the 14-hour window, the 30-minute break rule, and any applicable exception requirements.' },
    { id: 'reset-restart-p8', type: 'paragraph', text: 'Personal conveyance and other off-duty statuses can be sensitive. FMCSA has guidance on when personal conveyance can be combined with other off-duty time to complete a 10-hour or 34-hour break, but the movement must actually qualify as personal conveyance. Do not use personal conveyance as a workaround for carrier business or HOS pressure.' },
    { id: 'reset-restart-p9', type: 'paragraph', text: 'Passenger-carrying drivers have different daily limits. Passenger operations commonly use 8 consecutive hours off duty before the 10-hour driving limit, while property-carrying operations commonly use 10 consecutive hours off duty before the 11-hour driving limit. Confirm the correct rule set before applying this page.' },
    { id: 'reset-restart-p10', type: 'example', title: 'Example: 10-hour reset', text: 'A property-carrying driver finishes work and takes 10 consecutive hours off duty. If the driver is otherwise legal to drive, that rest period can reset the daily 11-hour driving limit and 14-hour window for the next duty period.' },
    { id: 'reset-restart-p11', type: 'example', title: 'Example: not a 34-hour restart', text: 'A driver takes 10 consecutive hours off duty and starts driving again. That may reset the daily clocks, but it does not restart the 60/70-hour cycle. The driver must still check available cycle hours.' },
    { id: 'reset-restart-p12', type: 'example', title: 'Example: 34-hour restart', text: 'A driver who is running low on 70-hour cycle time takes 34 consecutive hours off duty. If the restart is valid under the applicable rule and company policy, the driver may restart the 8-day cycle calculation. Daily limits still apply afterward.' },
    { id: 'reset-restart-p13', type: 'checklist', title: 'Quick reset/restart check', items: ['Confirm whether this is a property-carrying or passenger-carrying operation.', 'For a property-carrying daily reset, confirm 10 consecutive hours off duty or a valid sleeper berth method.', 'Do not count broken rest periods as a normal 10-hour reset unless a specific rule allows it.', 'For a cycle restart, confirm 34 or more consecutive hours off duty.', 'After any reset or restart, still check the 11-hour or applicable driving limit.', 'Still check the 14-hour or applicable duty window.', 'Still check the 30-minute break rule and 60/70-hour cycle status.', 'Verify the driver record, carrier policy, and official source before acting.'] },
    { id: 'reset-restart-p14', type: 'warning', title: 'No shortcut language', text: 'Do not say “I reset” without saying which reset. Daily reset and cycle restart are different. The safer language is: 10-hour daily reset, 34-hour cycle restart, or sleeper berth split calculation.' }
  ],
  audioScript: '10-hour reset and 34-hour restart. For many property-carrying drivers, 10 consecutive hours off duty is the normal reset before a new 11-hour driving limit and 14-hour driving window. A 34-hour restart is different. It can restart the 60 or 70-hour cycle calculation after 34 or more consecutive hours off duty. A 10-hour reset does not automatically restart the cycle. A 34-hour restart does not remove the need to follow daily limits after returning to work. Always verify the driver record, carrier policy, and official rule before relying on a reset or restart.',
  tags: ['10 hour reset', 'ten hour reset', '34 hour restart', 'thirty four hour restart', 'hos', 'off duty', 'consecutive hours', 'sleeper berth', 'cycle restart', '60 hour', '70 hour', 'personal conveyance'],
  sources: [
    { title: 'Summary of Hours of Service Regulations', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/summary-hours-service-regulations', note: 'FMCSA summary explaining 10 consecutive hours off duty for property-carrying drivers and the 34-hour restart.' },
    { title: '49 CFR Section 395.3', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-395.3', note: 'Official eCFR text for property-carrying HOS, including 10 consecutive hours off duty and 34-hour restart provisions.' },
    { title: 'Interstate Truck Driver\'s Guide to Hours of Service', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/interstate-truck-drivers-guide-hours-service', note: 'FMCSA driver guide explaining daily rest and restart concepts.' },
    { title: 'May sleeper berth time and off-duty periods be combined to meet the 10-hour off-duty requirement?', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/may-sleeper-berth-time-and-duty-periods-be-combined-meet-10-hour-duty', note: 'FMCSA guidance explaining consecutive sleeper berth/off-duty combinations for the 10-hour requirement.' },
    { title: 'Can personal conveyance time be combined with other off-duty time to complete a 10 or 34-hour break?', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/can-personal-conveyance-time-be-combined-other-duty-time-complete-10-or-34-hour', note: 'FMCSA ELD guidance on personal conveyance and off-duty breaks.' }
  ],
  lastReviewed: '2026-05-20'
};
