import type { GuidePage } from '../types/content';

export const bulkVsNonBulkPage: GuidePage = {
  id: 'bulk-vs-non-bulk',
  chapter: 16,
  title: 'Bulk vs Non-Bulk',
  category: 'hazmat-placards',
  summary: 'Bulk versus non-bulk packaging can change hazmat marking, placarding, identification-number display, and handling decisions. Do not guess from appearance alone.',
  content: [
    { id: 'bulk-vs-non-bulk-p1', type: 'summary', title: 'Why this matters', text: 'Bulk versus non-bulk is one of the biggest hazmat decision points. The same hazard class can lead to different marking, placarding, and identification-number-display requirements depending on whether the material is in bulk packaging or non-bulk packaging.' },
    { id: 'bulk-vs-non-bulk-p2', type: 'warning', title: 'Do not decide by “looks big”', text: 'A container looking large does not automatically mean it is bulk packaging, and a smaller-looking package is not automatically non-bulk. Use the regulatory definition, capacity, packaging type, shipping paper, and company hazmat procedure.' },
    { id: 'bulk-vs-non-bulk-p3', type: 'paragraph', text: 'Under the HMR definition in 49 CFR §171.8, bulk packaging generally means packaging, other than a vessel or barge, in which hazardous materials are loaded with no intermediate form of containment and which meets certain capacity thresholds.' },
    { id: 'bulk-vs-non-bulk-p4', type: 'paragraph', text: 'Common bulk packaging thresholds include a liquid receptacle with a maximum capacity greater than 450 liters or 119 gallons, a solid receptacle with a maximum net mass greater than 400 kilograms or 882 pounds and maximum capacity greater than 450 liters or 119 gallons, or a gas receptacle with a water capacity greater than 454 kilograms or 1,000 pounds.' },
    { id: 'bulk-vs-non-bulk-p5', type: 'paragraph', text: 'Non-bulk packaging is packaging that does not meet the bulk packaging definition. Many drums, boxes, pails, cylinders, and smaller packages can be non-bulk, but the correct answer depends on the actual capacity and regulatory definition, not casual naming.' },
    { id: 'bulk-vs-non-bulk-p6', type: 'paragraph', text: 'Bulk packaging can include cargo tanks, portable tanks, tank cars, intermediate bulk containers when they meet the bulk definition, and other large receptacles. Some packages people casually call totes or IBCs can cross the bulk threshold, so check capacity and markings.' },
    { id: 'bulk-vs-non-bulk-p7', type: 'paragraph', text: 'Bulk packages often have identification-number display requirements that are different from many non-bulk package shipments. Depending on the material and package, the identification number may need to appear on the bulk package, placard, orange panel, or white square-on-point display.' },
    { id: 'bulk-vs-non-bulk-p8', type: 'paragraph', text: 'Placarding can also change with bulk packaging. Some bulk packages and transport vehicles may need placards or identification-number displays even when a similar non-bulk shipment would be handled differently. The placarding table, aggregate quantity, package type, and exceptions all matter.' },
    { id: 'bulk-vs-non-bulk-p9', type: 'paragraph', text: 'Bulk versus non-bulk does not replace hazard class. You still need the proper shipping name, identification number, hazard class or division, packing group when assigned, quantity, and applicable special provisions or exceptions.' },
    { id: 'bulk-vs-non-bulk-p10', type: 'paragraph', text: 'The shipping paper should be checked before making a bulk/non-bulk decision. The packaging description, quantity, and material information can help confirm whether the package is bulk, non-bulk, or subject to a special rule.' },
    { id: 'bulk-vs-non-bulk-p11', type: 'paragraph', text: 'Company and site procedures may require extra checks before releasing bulk hazmat. Tank trucks, totes, cargo tanks, and large containers often involve loading/unloading procedures, segregation checks, seals, closures, residue rules, or customer-specific instructions.' },
    { id: 'bulk-vs-non-bulk-p12', type: 'paragraph', text: 'Residue can still matter. Empty or partially emptied bulk packaging can remain regulated when hazardous material residue is present unless an exception or cleaning/purging condition applies. Do not assume “empty” means unregulated.' },
    { id: 'bulk-vs-non-bulk-p13', type: 'example', title: 'Example: 55-gallon drum', text: 'A 55-gallon drum of a regulated liquid is typically below the 119-gallon liquid bulk threshold, so it is usually treated as non-bulk packaging. That does not mean it is unregulated; package labeling, marking, shipping papers, and placarding rules may still apply.' },
    { id: 'bulk-vs-non-bulk-p14', type: 'example', title: 'Example: 275-gallon tote', text: 'A 275-gallon liquid tote is above the 119-gallon liquid threshold and may be bulk packaging. That can change marking and identification-number-display requirements compared with smaller non-bulk packages.' },
    { id: 'bulk-vs-non-bulk-p15', type: 'example', title: 'Example: cargo tank', text: 'A cargo tank carrying hazardous material is a bulk package situation. Do not decide placards or identification-number displays by habit; confirm the material, identification number, placard requirements, and display method.' },
    { id: 'bulk-vs-non-bulk-p16', type: 'checklist', title: 'Quick bulk/non-bulk check', items: ['Start with the shipping paper and package information.', 'Identify whether the material is liquid, solid, or gas.', 'Check the package capacity or net mass against the bulk packaging thresholds.', 'Confirm whether hazardous material is loaded with no intermediate form of containment.', 'Check the proper shipping name, hazard class/division, identification number, and packing group when assigned.', 'Check bulk package marking requirements.', 'Check placard and identification-number-display requirements.', 'Check residue, empty-package, closure, and company procedure requirements.', 'Escalate unclear packaging or capacity questions to a trained hazmat/safety contact.'] },
    { id: 'bulk-vs-non-bulk-p17', type: 'warning', title: 'Bulk mistakes are high-risk', text: 'Bulk packaging errors can affect emergency response, placards, identification-number displays, inspections, and release risk. If the container size, shipping paper, placard, or displayed number does not make sense, stop and verify before the shipment moves.' }
  ],
  audioScript: 'Bulk versus non-bulk. Bulk packaging can change hazmat marking, placarding, and identification-number-display requirements. Do not decide by appearance alone. Under the HMR definition, common bulk thresholds include more than 119 gallons for liquids, more than 882 pounds and more than 119 gallons capacity for solids, and more than 1,000 pounds water capacity for gases. Non-bulk packaging does not meet the bulk definition. Bulk packages can include cargo tanks, portable tanks, tank cars, and some large totes or IBCs. Check the shipping paper, package capacity, material, hazard class, identification number, and current HMR before deciding. If the container, placard, number, or paperwork does not line up, stop and verify.',
  tags: ['bulk packaging', 'non-bulk packaging', '119 gallons', '450 liters', '882 pounds', '400 kilograms', '1000 pounds water capacity', 'cargo tank', 'portable tank', 'ibc', 'tote', 'identification number display', 'hazmat'],
  sources: [
    { title: '49 CFR Section 171.8 - Definitions and abbreviations', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-171.8', note: 'Official eCFR definitions for bulk packaging and non-bulk packaging.' },
    { title: 'Definition of Registration Terms', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/registration/definition-registration-terms', note: 'PHMSA page defining bulk packaging thresholds in plain language.' },
    { title: '49 CFR Section 172.302 - General marking requirements for bulk packagings', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.302', note: 'Official eCFR text for general marking requirements for bulk packagings.' },
    { title: '49 CFR Section 172.332 - Identification number markings', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.332', note: 'Official eCFR text for identification number markings.' },
    { title: '49 CFR Section 172.504 - General placarding requirements', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/172504', note: 'PHMSA regulatory text page for general placarding requirements.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' }
  ],
  lastReviewed: '2026-05-20'
};
