import type { GuidePage } from '../types/content';

export const placardDecisionGuidePage: GuidePage = {
  id: 'placard-decision-guide',
  chapter: 17,
  title: 'Placard Decision Guide',
  category: 'hazmat-placards',
  summary: 'A guided, plain-English process for deciding when placards or identification-number displays may be required, without replacing the HMR or qualified hazmat review.',
  content: [
    { id: 'placard-decision-guide-p1', type: 'summary', title: 'Use this as a decision path, not the final authority', text: 'Placarding decisions should follow the Hazardous Materials Regulations, the shipping paper, the material classification, quantity, packaging, and company procedure. This page gives a safe order of questions so users do not jump straight from a package label to a vehicle placard answer.' },
    { id: 'placard-decision-guide-p2', type: 'warning', title: 'Do not guess placards from habit', text: 'A driver saying “just give me flammable 3 placards” is not enough. A phone app, past load, package label, SDS, or habit does not replace checking the current shipping paper, packaging type, quantity, placarding table, and identification-number-display rules.' },
    { id: 'placard-decision-guide-p3', type: 'steps', title: 'Step 1: Start with the shipping paper', items: ['Confirm the material is regulated for transportation.', 'Find the proper shipping name.', 'Find the UN or NA identification number.', 'Find the hazard class or division.', 'Find the packing group when assigned.', 'Check quantity, number/type of packages, and packaging description.'] },
    { id: 'placard-decision-guide-p4', type: 'steps', title: 'Step 2: Check the Hazardous Materials Table', items: ['Use the shipping description to verify the material entry.', 'Check the hazard class or division.', 'Check label codes and special provisions.', 'Check whether any exception, limited quantity rule, or special handling rule may apply.', 'Do not use the table alone without reading the applicable sections and notes.'] },
    { id: 'placard-decision-guide-p5', type: 'steps', title: 'Step 3: Decide whether the material is Table 1 or Table 2', items: ['Under §172.504, Table 1 materials generally require placarding for any quantity.', 'Table 2 materials may depend on aggregate gross weight and other conditions.', 'Do not mix Table 1 and Table 2 logic.', 'Check whether subsidiary hazards or special rules change the answer.'] },
    { id: 'placard-decision-guide-p6', type: 'steps', title: 'Step 4: Check quantity and aggregation', items: ['For Table 2 materials, check the aggregate gross weight loaded on the transport vehicle or freight container.', 'Be careful when multiple compatible materials of the same or different hazard classes are loaded together.', 'Check whether “1,001 pounds or more” style placarding thresholds apply.', 'Do not ignore other materials already loaded on the trailer.'] },
    { id: 'placard-decision-guide-p7', type: 'steps', title: 'Step 5: Check bulk versus non-bulk', items: ['Identify whether the shipment includes bulk packaging.', 'Check bulk package marking and identification-number display requirements.', 'Do not assume a tote, tank, or large container is non-bulk.', 'Do not assume a non-bulk shipment has the same display requirements as a bulk package.'] },
    { id: 'placard-decision-guide-p8', type: 'steps', title: 'Step 6: Decide whether an identification number display is needed', items: ['Confirm the UN or NA number from the shipping paper.', 'Check whether the identification number must be displayed.', 'Check whether it belongs on the placard, orange panel, or white square-on-point display.', 'Confirm the displayed number matches the material and does not misidentify other materials.'] },
    { id: 'placard-decision-guide-p9', type: 'steps', title: 'Step 7: Check exceptions and special cases', items: ['Check limited quantity, materials of trade, residue, empty packaging, agriculture, and other relevant exceptions only when applicable.', 'Check whether domestic highway rules differ from vessel, air, or international requirements.', 'Check company and customer procedures when they are stricter.', 'Document or escalate the reason for the decision when required by procedure.'] },
    { id: 'placard-decision-guide-p10', type: 'paragraph', text: 'Placarding is not only about whether a placard is required. It also includes choosing the correct placard, making sure it is visible and in good condition, using identification numbers when required, and making sure the display matches the shipping papers and package markings.' },
    { id: 'placard-decision-guide-p11', type: 'paragraph', text: 'When the shipment includes more than one hazardous material, the decision can become more complex. Multiple hazard classes, aggregate weight, compatibility, bulk packaging, subsidiary risks, and identification-number display rules can all change the answer.' },
    { id: 'placard-decision-guide-p12', type: 'paragraph', text: 'A dangerous goods or hazmat app shown by a driver may be useful, but it is not the controlling document for your site. Use the shipment documents, official regulations, and qualified company safety process before releasing a load.' },
    { id: 'placard-decision-guide-p13', type: 'example', title: 'Example: Class 3 non-bulk packages', text: 'A few non-bulk packages with Class 3 labels may not require the same placarding treatment as a large bulk shipment. You still must check the total quantity, Table 2 threshold, exceptions, and other hazmat already loaded.' },
    { id: 'placard-decision-guide-p14', type: 'example', title: 'Example: bulk flammable liquid', text: 'A bulk flammable liquid shipment may need Class 3 placards and may also need the identification number displayed on the placard, orange panel, or white square-on-point display. A plain Class 3 placard may not be enough.' },
    { id: 'placard-decision-guide-p15', type: 'example', title: 'Example: mismatch before departure', text: 'The shipping paper lists one UN number, the package marking shows another, and the requested placard is only a hazard class placard. Do not pick the easiest placard. Stop, compare the documents, and escalate to a trained hazmat/safety contact.' },
    { id: 'placard-decision-guide-p16', type: 'checklist', title: 'Placard decision checklist', items: ['Start with the hazmat shipping paper.', 'Confirm proper shipping name, identification number, hazard class/division, and packing group when assigned.', 'Check the Hazardous Materials Table and applicable special provisions.', 'Determine whether the material falls under Table 1 or Table 2 placarding logic.', 'Check total quantity and aggregate gross weight where relevant.', 'Determine bulk versus non-bulk packaging.', 'Check whether placards are required.', 'Check whether an identification number display is required.', 'Check whether an exception or special case applies.', 'Compare the final display against shipping papers, package markings, and labels.', 'Escalate uncertainty before the shipment moves.'] },
    { id: 'placard-decision-guide-p17', type: 'warning', title: 'The safest answer is sometimes “pause the load”', text: 'If the paperwork, labels, markings, placards, identification numbers, or driver instructions do not match, the safest next step is not guessing. Pause the decision and involve a trained hazmat/safety contact.' }
  ],
  audioScript: 'Placard decision guide. Use this page as a decision path, not the final authority. Start with the shipping paper, then verify the Hazardous Materials Table, hazard class, identification number, quantity, packaging, and applicable exceptions. Check whether the material falls under Table 1 or Table 2 placarding logic. Check quantity and aggregate gross weight. Check whether the shipment is bulk or non-bulk. Then decide whether placards or identification-number displays are required. A driver asking for plain Class 3 placards is not enough. If the paperwork, labels, markings, placards, or identification numbers do not match, pause the load and escalate to a trained hazmat or safety contact.',
  tags: ['placard decision guide', 'placarding', 'table 1', 'table 2', '172.504', 'hazmat placards', 'identification number display', 'bulk', 'non-bulk', 'aggregate gross weight', 'class 3 placard', 'shipping papers'],
  sources: [
    { title: '49 CFR Section 172.504 - General placarding requirements', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/172504', note: 'PHMSA regulatory text page for general placarding requirements and placard tables.' },
    { title: '49 CFR Part 172 Subpart F - Placarding', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172/subpart-F', note: 'Official eCFR regulatory text for hazmat placarding requirements.' },
    { title: '49 CFR Section 172.101 - Hazardous Materials Table', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.101', note: 'Official eCFR Hazardous Materials Table.' },
    { title: '49 CFR Section 172.332 - Identification number markings', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.332', note: 'Official eCFR text for identification number markings.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' },
    { title: 'Hazmat Transportation Requirements PDF', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/hazmat-transportation-requirements-pdf', note: 'PHMSA training brochure covering shipping papers, marking, labeling, and placarding basics.' }
  ],
  lastReviewed: '2026-05-20'
};
