import type { GuidePage } from '../types/content';

export const hosExceptionsPage: GuidePage = {
  id: 'hos-exceptions',
  chapter: 10,
  title: 'HOS Exceptions',
  category: 'hos',
  summary: 'Common hours-of-service exceptions can change logging, break, driving-window, or recordkeeping requirements, but only when every condition of the specific exception is met.',
  content: [
    { id: 'hos-exceptions-p1', type: 'summary', title: 'The safe way to think about exceptions', text: 'An HOS exception is not a permission slip to ignore the rules. It is a narrow rule that applies only when the driver, vehicle, cargo, route, distance, time records, and operation meet the official conditions for that specific exception.' },
    { id: 'hos-exceptions-p2', type: 'warning', title: 'Do not stack exceptions casually', text: 'Drivers should not mix exception language from different rules. A short-haul exception, adverse driving conditions exception, agriculture exemption, emergency condition rule, and sleeper berth provision each have different triggers and limits. Verify the exact exception before relying on it.' },
    { id: 'hos-exceptions-p3', type: 'paragraph', text: 'The short-haul exception is one of the most common HOS exceptions. Under current FMCSA summaries, qualifying drivers using the §395.1(e)(1) short-haul exception must operate within a 150 air-mile radius, report and return to the normal work reporting location, and stay within the allowed duty-period conditions.' },
    { id: 'hos-exceptions-p4', type: 'paragraph', text: 'A short-haul driver who qualifies may be exempt from keeping the normal driver record of duty status and from the 30-minute break requirement, but the carrier must keep accurate time records. Short-haul does not mean “no rules.” It means a different recordkeeping setup when all conditions are met.' },
    { id: 'hos-exceptions-p5', type: 'paragraph', text: 'The adverse driving conditions exception may allow extra time when unexpected adverse conditions are encountered after dispatch and could not reasonably have been known before the trip. Under current FMCSA materials, the 2020 rule expanded the driving window during adverse driving conditions by up to 2 additional hours.' },
    { id: 'hos-exceptions-p6', type: 'warning', title: 'Adverse driving is not normal traffic', text: 'Adverse driving conditions are not the same as predictable rush-hour traffic, regular congestion, normal loading delays, poor trip planning, or detention that could have been anticipated. The condition must meet the official definition and the extension should match the time actually needed.' },
    { id: 'hos-exceptions-p7', type: 'paragraph', text: 'The 16-hour short-haul exception is a specific property-carrying exception for certain drivers who return to the normal work reporting location. It is limited and cannot be treated as a general extra-workday rule. Drivers should verify the exact §395.1(o) conditions before relying on it.' },
    { id: 'hos-exceptions-p8', type: 'paragraph', text: 'Agricultural operations have special HOS treatment in certain circumstances. FMCSA describes agricultural commodity transportation within a 150 air-mile radius from the source during state-determined planting and harvesting periods as excepted from certain HOS rules. Once outside the qualifying radius or outside the conditions of the exception, normal HOS requirements may apply again depending on the trip and applicable FMCSA guidance.' },
    { id: 'hos-exceptions-p9', type: 'paragraph', text: 'Emergency conditions can change HOS requirements when an emergency relief rule or declaration applies, but drivers and carriers should confirm the declaration, covered area, covered operations, dates, and limits. “It felt urgent” is not the same as operating under an official emergency condition or declaration.' },
    { id: 'hos-exceptions-p10', type: 'paragraph', text: 'Passenger-carrying exceptions and property-carrying exceptions are not always the same. Some summaries include both, but this guide uses property-carrying examples unless a page says otherwise. Always confirm the correct rule set for the operation.' },
    { id: 'hos-exceptions-p11', type: 'example', title: 'Example: short-haul works only if the conditions fit', text: 'A driver stays within 150 air miles, reports to the normal work reporting location, returns within the allowed period, and the carrier keeps required time records. That may fit the short-haul exception. If the driver goes beyond the radius or does not return as required, the exception may no longer apply.' },
    { id: 'hos-exceptions-p12', type: 'example', title: 'Example: adverse weather', text: 'A driver encounters an unexpected road closure from a sudden storm that could not reasonably have been known before dispatch. The adverse driving conditions exception may be relevant. If the delay was normal rush-hour traffic the driver should have expected, the exception likely does not fit.' },
    { id: 'hos-exceptions-p13', type: 'example', title: 'Example: agriculture radius', text: 'A driver hauling qualifying agricultural commodities during a state planting or harvesting period may have special HOS treatment within the 150 air-mile radius from the source. After leaving the qualifying radius or operation, the driver may need to resume normal logging and HOS compliance.' },
    { id: 'hos-exceptions-p14', type: 'checklist', title: 'Exception checklist', items: ['Name the exact exception before using it.', 'Confirm whether the driver is property-carrying or passenger-carrying.', 'Confirm the distance/radius limit, if any.', 'Confirm required return-to-work-location conditions, if any.', 'Confirm duty-period limits and time-record requirements.', 'Confirm whether the exception affects logging, breaks, the driving window, or only a specific limit.', 'Confirm state/intrastate rules and employer policy.', 'Document or annotate the reason when the ELD/log or company procedure requires it.', 'If unsure, follow the normal HOS rule and ask a qualified safety contact.'] },
    { id: 'hos-exceptions-p15', type: 'warning', title: 'When in doubt, do not self-invent an exception', text: 'A real exception has official conditions. If the driver cannot clearly name the exception and explain why every condition is met, the safer answer is to verify before driving.' }
  ],
  audioScript: 'HOS exceptions. An hours-of-service exception is not permission to ignore the rules. It only applies when every official condition for that specific exception is met. Common examples include short-haul, adverse driving conditions, certain 16-hour short-haul situations, agricultural operations, and emergency conditions. Short-haul can change normal logging and break requirements, but only when the distance, reporting-location, time-record, and duty-period conditions are met. Adverse driving conditions are not normal traffic or poor planning. Agricultural and emergency exceptions have their own limits. If the driver cannot clearly name the exception and show that every condition is met, verify before driving.',
  tags: ['hos exceptions', 'short haul', '150 air mile', 'adverse driving conditions', '16 hour exception', 'agriculture exemption', 'emergency conditions', 'time records', 'eld', 'property carrying'],
  sources: [
    { title: 'Hours of Service Exceptions', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/hours-service-exceptions', note: 'FMCSA guidance and FAQs for HOS exceptions.' },
    { title: 'Summary of Hours of Service Regulations', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/summary-hours-service-regulations', note: 'FMCSA summary covering short-haul, adverse driving conditions, and other HOS topics.' },
    { title: 'Hours of Service Drivers Final Rule', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/hours-service-drivers-final-rule', note: 'FMCSA summary of the 2020 changes to short-haul, adverse driving, break, and sleeper berth provisions.' },
    { title: 'Interstate Truck Driver\'s Guide to Hours of Service', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/interstate-truck-drivers-guide-hours-service', note: 'FMCSA guide with examples and appendix coverage of HOS exceptions.' },
    { title: 'Electronic Logging Devices, Hours of Service, and Agricultural Exemptions', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/electronic-logging-devices-elds-hours-service-hos-and-agricultural-exemptions', note: 'FMCSA explanation of agricultural commodity HOS exemptions and ELD handling.' },
    { title: '49 CFR Section 395.1 - Scope of rules in this part', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-395.1', note: 'Official eCFR text covering scope and exceptions in Part 395.' }
  ],
  lastReviewed: '2026-05-20'
};
