import type { GuidePage } from '../types/content';

export const sleeperBerthPage: GuidePage = {
  id: 'sleeper-berth',
  chapter: 9,
  title: 'Sleeper Berth / Split Sleeper',
  category: 'hos',
  summary: 'Sleeper berth rules can let qualifying rest periods satisfy the required 10-hour off-duty period and affect the 14-hour driving window, but only when the split is used correctly.',
  content: [
    { id: 'sleeper-berth-p1', type: 'summary', title: 'The short version', text: 'For many property-carrying drivers, sleeper berth rules allow the required 10-hour off-duty period to be taken in specific qualifying parts instead of one straight 10-hour break. The current federal split sleeper rule generally requires one period of at least 7 consecutive hours in the sleeper berth and another period of at least 2 consecutive hours off duty, in the sleeper berth, or a qualifying combination, with the paired periods totaling at least 10 hours.' },
    { id: 'sleeper-berth-p2', type: 'warning', title: 'This is an advanced HOS topic', text: 'Do not guess on split sleeper. The exact order, length, status, and pairing of rest periods matters. A driver should verify the ELD/log calculation, carrier policy, and official FMCSA rule before relying on split sleeper to keep driving.' },
    { id: 'sleeper-berth-p3', type: 'paragraph', text: 'The sleeper berth rule is different from simply taking a normal break. A short rest stop, nap, meal break, or ordinary 30-minute break does not automatically create a split sleeper calculation. The rest periods must meet the official sleeper berth requirements.' },
    { id: 'sleeper-berth-p4', type: 'paragraph', text: 'One qualifying period must be at least 7 consecutive hours in the sleeper berth. The other qualifying period must be at least 2 consecutive hours and may be off duty, in the sleeper berth, or a qualifying combination of the two. When paired, the two periods must total at least 10 hours.' },
    { id: 'sleeper-berth-p5', type: 'paragraph', text: 'Common property-carrying examples include 8/2 and 7/3 splits. Other pairings can qualify when they meet the minimums, such as 7.5 hours in the sleeper berth paired with 2.5 qualifying hours. The key is that one period meets the sleeper berth minimum, the other meets the 2-hour minimum, and the two total at least 10 hours.' },
    { id: 'sleeper-berth-p6', type: 'paragraph', text: 'When the qualifying sleeper berth periods are paired correctly, FMCSA guidance explains that neither qualifying period counts against the 14-hour driving window. This can change the driver’s available window, but it does not erase the 11-hour driving limit, 30-minute break rule, or 60/70-hour cycle limit.' },
    { id: 'sleeper-berth-p7', type: 'paragraph', text: 'The order can vary. A driver may take the shorter qualifying period first and the sleeper period later, or the sleeper period first and the shorter qualifying period later. The driver still has to pair the correct periods and calculate the next available driving window correctly.' },
    { id: 'sleeper-berth-p8', type: 'paragraph', text: 'A sleeper berth period shorter than 2 hours should not be used to accumulate the required 10 hours under the sleeper berth provision. Very short sleeper time may be useful for rest, but it generally does not qualify as part of the split sleeper calculation.' },
    { id: 'sleeper-berth-p9', type: 'paragraph', text: 'A split sleeper calculation does not create more than the legal driving limit. After a valid split, the driver must still track total driving time, the recalculated driving window, the 30-minute break rule, and the 60/70-hour cycle.' },
    { id: 'sleeper-berth-p10', type: 'paragraph', text: 'FMCSA has discussed pilot programs for additional sleeper berth flexibility, but pilot programs are not the same as the normal rule for every driver. Unless a driver is officially operating under an approved program or exemption, do not treat pilot-program options as generally available.' },
    { id: 'sleeper-berth-p11', type: 'paragraph', text: 'Passenger-carrying sleeper berth rules are different. Passenger-carrying CMVs equipped with a sleeper berth have their own requirements under the passenger HOS framework. This page is written primarily for property-carrying split sleeper basics.' },
    { id: 'sleeper-berth-p12', type: 'example', title: 'Example: 8/2 split', text: 'A property-carrying driver takes 8 consecutive hours in the sleeper berth and later takes 2 consecutive hours off duty. If those periods are properly paired and all other conditions are met, they can satisfy the split sleeper requirement because one period is at least 7 hours in the sleeper berth, the other is at least 2 qualifying hours, and the total is at least 10 hours.' },
    { id: 'sleeper-berth-p13', type: 'example', title: 'Example: 7/3 split', text: 'A driver takes 7 consecutive hours in the sleeper berth and later takes 3 consecutive hours off duty. This can be a valid split sleeper pattern when properly paired and recorded because the periods meet the 7-hour sleeper berth minimum, the 2-hour minimum, and the 10-hour total.' },
    { id: 'sleeper-berth-p14', type: 'example', title: 'Example: not enough sleeper berth time', text: 'A driver takes 6 hours in the sleeper berth and 4 hours off duty. That may total 10 hours of rest, but under the normal current split sleeper rule, it does not meet the requirement for at least 7 consecutive hours in the sleeper berth unless a specific approved exception or pilot program applies.' },
    { id: 'sleeper-berth-p15', type: 'checklist', title: 'Quick split sleeper check', items: ['Confirm this is a property-carrying operation using the federal sleeper berth provision.', 'Confirm one rest period is at least 7 consecutive hours in the sleeper berth.', 'Confirm the second rest period is at least 2 consecutive qualifying hours.', 'Confirm the paired periods total at least 10 hours.', 'Confirm the periods are recorded in the correct duty statuses.', 'Confirm the ELD/log pairs the intended periods correctly.', 'Recalculate the 14-hour window using the official sleeper berth method.', 'Check the 11-hour driving limit, 30-minute break rule, and 60/70-hour cycle separately.', 'Do not use pilot-program split options unless the driver is actually approved to operate under that program or exemption.'] },
    { id: 'sleeper-berth-p16', type: 'warning', title: 'Use the log, not memory', text: 'Split sleeper errors are easy because the calculation depends on actual duty statuses and timing. Use the driver’s ELD/log display, carrier guidance, and official FMCSA source before making a driving decision.' }
  ],
  audioScript: 'Sleeper berth and split sleeper. For many property-carrying drivers, the sleeper berth rule can allow the required 10-hour off-duty period to be taken in two qualifying parts. One period must be at least 7 consecutive hours in the sleeper berth. The other must be at least 2 consecutive qualifying hours off duty, in the sleeper berth, or a qualifying combination. The two periods together must total at least 10 hours. When paired correctly, the qualifying periods do not count against the 14-hour driving window. Split sleeper does not erase the 11-hour driving limit, the 30-minute break rule, or the 60/70-hour cycle. Do not guess on split sleeper; verify the log and official source.',
  tags: ['sleeper berth', 'split sleeper', '8/2 split', '7/3 split', 'hos', '14 hour window', '10 hour off duty', 'property carrying', 'qualifying rest period', 'eld'],
  sources: [
    { title: 'Summary of Hours of Service Regulations', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/summary-hours-service-regulations', note: 'FMCSA summary explaining split sleeper periods totaling at least 10 hours with one period at least 7 hours in the sleeper berth and another at least 2 hours.' },
    { title: 'What rest periods qualify for the split sleeper berth provision?', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/what-rest-periods-qualify-split-sleeper-berth-provision', note: 'FMCSA FAQ explaining qualifying 7-hour sleeper berth and 2-hour qualifying rest periods.' },
    { title: 'How are split sleeper berth rest periods used in determining compliance with the 14-hour driving window rule?', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/how-are-split-sleeper-berth-rest-periods-used-determining-compliance-14', note: 'FMCSA FAQ explaining how paired qualifying periods affect the 14-hour window.' },
    { title: 'A driver takes 5 consecutive hours off duty and later takes a 7-hour consecutive break in the sleeper berth. How is this time calculated?', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/driver-takes-5-consecutive-hours-duty-and-later-takes-7-hour-consecutive', note: 'FMCSA example showing qualifying split sleeper periods and exclusion from the 14-hour window.' },
    { title: 'May a sleeper berth be used for a period of less than 2 hours duration?', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/may-sleeper-berth-be-used-period-less-2-hours-duration', note: 'FMCSA guidance stating sleeper berth periods under 2 hours may not be used to accumulate the required 10 hours under §395.3.' },
    { title: '49 CFR Part 395 - Hours of Service of Drivers', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-395', note: 'Official eCFR regulatory text for federal HOS rules.' }
  ],
  lastReviewed: '2026-05-20'
};
