import type { GuidePage } from '../types/content';

export const hazmatBasicsPage: GuidePage = {
  id: 'hazmat-basics',
  chapter: 12,
  title: 'Hazmat Basics',
  category: 'hazmat-placards',
  summary: 'A plain-English starting point for hazardous materials transportation: what hazmat means, who regulates it, and why shipping papers, labels, markings, placards, training, and emergency information matter.',
  content: [
    { id: 'hazmat-basics-p1', type: 'summary', title: 'What hazmat means in transportation', text: 'In transportation, hazardous material means a material that is regulated because it can pose an unreasonable risk to health, safety, or property when transported in commerce. The U.S. hazardous materials transportation rules are mainly found in the Hazardous Materials Regulations, or HMR, in Title 49 CFR Parts 171 through 180.' },
    { id: 'hazmat-basics-p2', type: 'warning', title: 'This chapter is only a starting point', text: 'Hazmat decisions should not be made from memory or from this app alone. Classification, packaging, shipping papers, marking, labeling, placarding, emergency response information, registration, training, and modal rules can all matter. Use the official PHMSA/eCFR sources and qualified company procedures before acting.' },
    { id: 'hazmat-basics-p3', type: 'paragraph', text: 'PHMSA is the main U.S. Department of Transportation agency responsible for the Hazardous Materials Regulations. PHMSA says the HMR govern the safe transportation of hazardous materials in commerce and include requirements for classification, communication, packaging, handling, and transportation.' },
    { id: 'hazmat-basics-p4', type: 'paragraph', text: 'A hazmat shipment usually starts with the material identification and classification. The correct proper shipping name, hazard class or division, identification number, packing group when assigned, quantity, and packaging information drive many downstream requirements. Hazmat classification is generally the shipper or offeror’s responsibility, and employees should only perform hazmat functions they are trained and authorized to perform.' },
    { id: 'hazmat-basics-p5', type: 'paragraph', text: 'The Hazardous Materials Table in 49 CFR §172.101 is a central tool for identifying regulated materials and finding requirements. It can point to hazard class, identification number, label codes, special provisions, packaging authorizations, quantity limits, and vessel stowage information.' },
    { id: 'hazmat-basics-p6', type: 'paragraph', text: 'Shipping papers are a primary communication tool. They tell carriers, drivers, enforcement, and emergency responders what hazardous material is being transported. The shipping paper information must be clear and must match the regulated material and shipment.' },
    { id: 'hazmat-basics-p7', type: 'paragraph', text: 'Package labels, package markings, placards, identification number displays, and emergency response information are related but different parts of the hazmat communication system. Do not treat a placard, a package label, a UN number, or an SDS as if they all answer the same question.' },
    { id: 'hazmat-basics-p8', type: 'paragraph', text: 'Placards communicate hazard class information on vehicles or transport units when required. PHMSA explains that placards help transportation workers, enforcement personnel, and emergency responders quickly identify the general hazard involved in a shipment.' },
    { id: 'hazmat-basics-p9', type: 'paragraph', text: 'A numbered placard, orange panel, or white square-on-point display can show a four-digit identification number. Whether a specific shipment needs a hazard class placard only, an identification number display, a bulk package marking, or another display depends on the material, quantity, packaging, and regulation.' },
    { id: 'hazmat-basics-p10', type: 'paragraph', text: 'Bulk versus non-bulk matters. Packaging size and type can change marking, placarding, and identification-number-display requirements. Do not guess from the look of the container; check the definition, capacity, and shipment information.' },
    { id: 'hazmat-basics-p11', type: 'paragraph', text: 'Hazmat employees must be trained for the functions they perform. PHMSA training materials explain that hazmat employees need general awareness/familiarization, function-specific training, safety training, security awareness, and in-depth security training when a security plan is required. Drivers may also need driver-specific training and CDL endorsements depending on the operation.' },
    { id: 'hazmat-basics-p12', type: 'paragraph', text: 'GHS/SDS information and DOT hazmat transportation rules are connected to chemical safety, but they are not the same system. An SDS can be useful background, but transportation decisions still need the shipping paper, classification, packaging, and HMR requirements.' },
    { id: 'hazmat-basics-p13', type: 'paragraph', text: 'Employer and carrier procedures can be stricter than the minimum federal rule. A driver or dock worker may need to follow company hazmat procedures, site rules, customer instructions, emergency response procedures, or state/intrastate requirements in addition to the federal HMR.' },
    { id: 'hazmat-basics-p14', type: 'example', title: 'Example: label does not answer placarding by itself', text: 'A package has a Class 3 flammable liquid label. That label tells you something important about the package hazard, but it does not by itself answer whether the truck needs placards or whether an identification number must be displayed. You still need the shipping paper, quantity, packaging type, and the placarding rules.' },
    { id: 'hazmat-basics-p15', type: 'example', title: 'Example: SDS is not the shipping paper', text: 'An SDS may describe chemical hazards, handling, and emergency information, but the shipping paper is the transportation document used to communicate regulated hazmat shipping information. Do not replace one with the other.' },
    { id: 'hazmat-basics-p16', type: 'example', title: 'Example: bulk package changes the question', text: 'A small drum and a cargo tank may contain a similar hazard class material, but the bulk package can trigger different marking, placarding, and identification-number-display requirements. Packaging type matters.' },
    { id: 'hazmat-basics-p17', type: 'checklist', title: 'Quick hazmat basics check', items: ['Identify the material and whether it is regulated for transportation.', 'Check the proper shipping name, hazard class/division, identification number, and packing group when assigned.', 'Review the shipping paper before making transport decisions.', 'Check packaging type and quantity, including bulk versus non-bulk.', 'Check required package labels and markings.', 'Check required vehicle/container placards and identification-number displays.', 'Confirm emergency response information is available when required.', 'Confirm the driver and hazmat employees have required training and endorsements for their functions.', 'Verify against current PHMSA/eCFR sources and company procedures before acting.'] },
    { id: 'hazmat-basics-p18', type: 'warning', title: 'When unsure, stop and verify', text: 'Hazmat mistakes can create serious safety and enforcement problems. If the shipping paper, labels, markings, placards, SDS, or driver instructions do not line up, do not guess. Escalate to a qualified hazmat/safety contact and verify the current regulation.' }
  ],
  audioScript: 'Hazmat basics. In transportation, hazardous material means a material regulated because it can pose an unreasonable risk to health, safety, or property when transported in commerce. The main U.S. hazardous materials transportation rules are in 49 CFR Parts 171 through 180. Hazmat decisions usually start with material identification and classification, including proper shipping name, hazard class or division, identification number, packing group when assigned, quantity, and packaging. Hazmat classification is generally the shipper or offeror’s responsibility, and employees should only perform hazmat functions they are trained and authorized to perform. Shipping papers, labels, markings, placards, identification number displays, and emergency response information are related but different. GHS and SDS information is not the same as DOT transportation compliance. If anything does not line up, stop and verify with official sources and a qualified safety contact.',
  tags: ['hazmat basics', 'hazardous materials', 'phmsa', 'hmr', '49 cfr 171', '49 cfr 172', 'hazardous materials table', 'shipping papers', 'placards', 'labels', 'markings', 'un number', 'na number', 'bulk packaging', 'sds', 'ghs', 'hazmat training'],
  sources: [
    { title: 'Hazardous Materials Regulations', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/standards-rulemaking/hazmat/hazardous-materials-regulations', note: 'PHMSA overview of the Hazardous Materials Regulations and eCFR Title 49 CFR Parts 100-185.' },
    { title: 'How to Use the Hazardous Materials Regulations', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/sites/phmsa.dot.gov/files/docs/training/hazmat/28426/how-use-hmr-final-web.pdf', note: 'PHMSA guide explaining how the HMR are organized and how to use the Hazardous Materials Table.' },
    { title: 'Identifying Hazardous Materials in Your Community', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/standards-rulemaking/hazmat/identifying-hazardous-materials-in-your-community', note: 'PHMSA explanation of placards, hazard communication, and identification numbers.' },
    { title: 'Training Requirements for Industry', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/training-requirements-industry', note: 'PHMSA overview of hazmat training requirements for hazmat employees and employers.' },
    { title: 'Hazmat Transportation Training Requirements', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/hazmat-transportation-training-requirements', note: 'PHMSA training resource covering HMR training categories.' },
    { title: '49 CFR Part 171 - General Information, Regulations, and Definitions', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-171', note: 'Official eCFR regulatory text for general hazmat information, definitions, and applicability.' },
    { title: '49 CFR Section 172.101 - Hazardous Materials Table', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-172.101', note: 'Official eCFR Hazardous Materials Table.' },
    { title: '49 CFR Part 172 - Hazardous Materials Table, Special Provisions, Communications, Emergency Response Information, Training Requirements, and Security Plans', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172', note: 'Official eCFR regulatory text for hazmat communication, training, and security plan requirements.' }
  ],
  lastReviewed: '2026-05-20'
};
