import type { GuidePage } from '../types/content';

export const sdsExplainedPage: GuidePage = {
  id: 'sds-explained',
  chapter: 21,
  title: 'SDS Explained',
  category: 'ghs-sds',
  summary: 'Safety Data Sheets give detailed workplace chemical hazard information in a standardized 16-section format. They help with safe handling, storage, PPE, emergency response, and transport awareness.',
  content: [
    { id: 'sds-explained-p1', type: 'summary', title: 'What an SDS is', text: 'SDS means Safety Data Sheet. OSHA uses SDSs under the Hazard Communication Standard to communicate detailed information about hazardous chemicals, including hazards, protective measures, and safety precautions for handling, storing, and responding to emergencies.' },
    { id: 'sds-explained-p2', type: 'warning', title: 'An SDS is not the same as a hazmat shipping paper', text: 'An SDS can include transport information, but it does not automatically replace a DOT hazmat shipping paper, package label, marking, placard, or identification-number display. For transportation compliance, verify the shipping paper and Hazardous Materials Regulations.' },
    { id: 'sds-explained-p3', type: 'paragraph', text: 'OSHA requires SDS information to be presented in a consistent 16-section format. This structure helps workers, supervisors, emergency responders, and safety personnel quickly find the same type of information across different chemicals.' },
    { id: 'sds-explained-p4', type: 'paragraph', text: 'Section 1 identifies the product and supplier. It normally includes the product identifier, recommended use, restrictions on use, supplier information, and emergency phone number.' },
    { id: 'sds-explained-p5', type: 'paragraph', text: 'Section 2 gives hazard identification. This is where workers look for hazard classification, signal word, hazard statements, pictograms, precautionary statements, and hazards not otherwise classified when applicable.' },
    { id: 'sds-explained-p6', type: 'paragraph', text: 'Section 3 covers composition and ingredient information. It can identify hazardous ingredients, concentration ranges, and chemical identity information, subject to trade secret rules where allowed.' },
    { id: 'sds-explained-p7', type: 'paragraph', text: 'Section 4 covers first-aid measures. It explains important symptoms and recommended first-aid actions for exposure routes such as inhalation, skin contact, eye contact, or ingestion.' },
    { id: 'sds-explained-p8', type: 'paragraph', text: 'Section 5 covers firefighting measures. It can include suitable extinguishing media, fire hazards, hazardous combustion products, and protective equipment or precautions for firefighters.' },
    { id: 'sds-explained-p9', type: 'paragraph', text: 'Section 6 covers accidental release measures. It can include spill response, containment, cleanup methods, and precautions for responders or workers near the release.' },
    { id: 'sds-explained-p10', type: 'paragraph', text: 'Section 7 covers handling and storage. This section is important for everyday work because it can describe safe handling practices, incompatible materials, storage conditions, and special precautions.' },
    { id: 'sds-explained-p11', type: 'paragraph', text: 'Section 8 covers exposure controls and personal protection. Workers often use this section to find exposure limits, engineering controls, ventilation guidance, and PPE recommendations such as gloves, eye protection, respirators, or protective clothing.' },
    { id: 'sds-explained-p12', type: 'paragraph', text: 'Sections 9 through 11 cover physical and chemical properties, stability and reactivity, and toxicological information. These sections can help explain why the chemical behaves the way it does and what health effects may be possible.' },
    { id: 'sds-explained-p13', type: 'paragraph', text: 'Sections 12 through 15 cover ecological information, disposal considerations, transport information, and regulatory information. OSHA does not enforce the content of these sections, but they are still part of the standardized SDS format and can be useful depending on the question.' },
    { id: 'sds-explained-p14', type: 'paragraph', text: 'Section 16 covers other information, including the date of preparation or last revision. This helps users see whether the SDS may be outdated and whether the version should be verified with the supplier or company SDS system.' },
    { id: 'sds-explained-p15', type: 'paragraph', text: 'Employers must ensure SDSs are readily accessible to employees in their work areas during each work shift when they may be exposed to hazardous chemicals. Accessibility can be paper, electronic, or another method that works reliably under workplace conditions.' },
    { id: 'sds-explained-p16', type: 'paragraph', text: 'A missing, outdated, or conflicting SDS should be escalated. Workers should not guess PPE, storage, spill response, or first aid when the SDS is unavailable or does not match the container label or product in use.' },
    { id: 'sds-explained-p17', type: 'example', title: 'Example: choosing gloves', text: 'A worker sees a corrosive pictogram on a label. The SDS, especially Section 8, can help identify recommended protective gloves, eye protection, and other exposure controls instead of guessing from the pictogram alone.' },
    { id: 'sds-explained-p18', type: 'example', title: 'Example: transport information', text: 'SDS Section 14 may list transport information such as UN number, proper shipping name, hazard class, or packing group. That information should still be verified against the actual shipping paper and current DOT hazmat requirements before transportation decisions are made.' },
    { id: 'sds-explained-p19', type: 'example', title: 'Example: old SDS', text: 'A chemical container has a newer product name than the SDS in the binder. Do not assume the old SDS applies. Verify the product identifier, supplier, revision date, and company SDS system before relying on it.' },
    { id: 'sds-explained-p20', type: 'checklist', title: 'Quick SDS check', items: ['Confirm the product identifier matches the container.', 'Check Section 2 for hazards, signal word, pictograms, and hazard statements.', 'Check Section 4 for first aid.', 'Check Section 5 for firefighting information.', 'Check Section 6 for spill response.', 'Check Section 7 for handling and storage.', 'Check Section 8 for exposure controls and PPE.', 'Check Section 14 only as transport information support, not as a replacement for shipping papers.', 'Check Section 16 for revision date.', 'Escalate missing, outdated, or conflicting SDS information.'] },
    { id: 'sds-explained-p21', type: 'warning', title: 'Do not use an SDS as permission to improvise', text: 'The SDS helps explain hazards and precautions, but workers still need training, employer procedures, site rules, and qualified safety guidance. When the SDS and workplace reality do not line up, pause and verify.' }
  ],
  audioScript: 'SDS explained. SDS means Safety Data Sheet. OSHA uses Safety Data Sheets under the Hazard Communication Standard to communicate detailed information about hazardous chemicals. SDSs use a standardized 16-section format. Key sections include identification, hazard identification, composition, first aid, firefighting, accidental release, handling and storage, exposure controls and PPE, physical and chemical properties, stability and reactivity, toxicology, ecological information, disposal, transport, regulatory information, and other information. SDSs must be readily accessible to employees in their work areas during each work shift. An SDS can support safety and transport awareness, but it does not replace a DOT hazmat shipping paper or placarding decision.',
  tags: ['sds', 'safety data sheet', 'osha sds', 'hazcom', 'section 2', 'section 4', 'section 7', 'section 8', 'section 14', 'ppe', 'first aid', 'spill response', 'transport information'],
  sources: [
    { title: 'Safety Data Sheets QuickCard', agency: 'OSHA', url: 'https://obis.osha.gov/Publications/HazComm_QuickCard_SafetyData.html', note: 'OSHA quick reference explaining SDS purpose and the 16-section format.' },
    { title: 'Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/', note: 'OSHA overview of HazCom, labels, SDSs, and training.' },
    { title: '29 CFR 1910.1200 - Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200', note: 'Official OSHA regulatory text for the Hazard Communication Standard.' },
    { title: 'Hazard Communication Questions and Answers', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/faq', note: 'OSHA FAQ for SDS accessibility and HazCom implementation questions.' },
    { title: 'BRIEF: Hazard Communication Standard: Safety Data Sheets', agency: 'OSHA', url: 'https://www.osha.gov/sites/default/files/publications/OSHA3514.pdf', note: 'OSHA brief explaining the required SDS sections and employee access.' }
  ],
  lastReviewed: '2026-05-20'
};
