import type { GuidePage } from '../types/content';

export const ghsPictogramsPage: GuidePage = {
  id: 'ghs-pictograms',
  chapter: 20,
  title: 'GHS Pictograms',
  category: 'ghs-sds',
  summary: 'GHS pictograms are red-diamond workplace chemical hazard symbols used under OSHA HazCom. They point to hazard types, but they do not replace SDSs, training, or DOT transportation labels and placards.',
  content: [
    { id: 'ghs-pictograms-p1', type: 'summary', title: 'What pictograms do', text: 'GHS pictograms give a quick visual warning about chemical hazards. Under OSHA HazCom, pictograms are part of workplace chemical labels and are meant to help workers quickly recognize hazard categories such as flammability, corrosion, toxicity, gases under pressure, or health hazards.' },
    { id: 'ghs-pictograms-p2', type: 'warning', title: 'A pictogram is not the whole answer', text: 'A pictogram is a warning symbol, not a complete chemical safety plan. Always read the label text, signal word, hazard statements, precautionary statements, and Safety Data Sheet. Do not use a GHS pictogram alone to make DOT placarding or shipping-paper decisions.' },
    { id: 'ghs-pictograms-p3', type: 'paragraph', text: 'OSHA pictograms have a black hazard symbol on a white background inside a red diamond border. The red diamond shape is part of the HazCom visual system and helps workers identify the symbol as a chemical hazard communication pictogram.' },
    { id: 'ghs-pictograms-p4', type: 'paragraph', text: 'OSHA requires eight pictograms under the Hazard Communication Standard. The environmental pictogram exists in the GHS system, but OSHA does not enforce it as a mandatory HazCom pictogram because environmental hazards are outside OSHA’s jurisdiction.' },
    { id: 'ghs-pictograms-p5', type: 'paragraph', text: 'The flame pictogram points to flammability-related hazards. It can be used for hazards such as flammables, pyrophorics, self-heating chemicals, chemicals that emit flammable gas, self-reactives, and organic peroxides depending on classification.' },
    { id: 'ghs-pictograms-p6', type: 'paragraph', text: 'The flame-over-circle pictogram points to oxidizers. Oxidizers can cause or intensify fire and should not be treated as ordinary flammable materials. Read the SDS and storage guidance before handling or storing oxidizers near incompatible materials.' },
    { id: 'ghs-pictograms-p7', type: 'paragraph', text: 'The exploding bomb pictogram points to explosion or severe reactivity hazards. It can apply to explosives, some self-reactives, and some organic peroxides depending on classification. These hazards require careful handling and trained review.' },
    { id: 'ghs-pictograms-p8', type: 'paragraph', text: 'The corrosion pictogram can point to skin corrosion, serious eye damage, or corrosive effects on metals. Do not assume all corrosive-looking hazards are the same; read the hazard statements and SDS for the exact hazard and required precautions.' },
    { id: 'ghs-pictograms-p9', type: 'paragraph', text: 'The skull and crossbones pictogram points to acute toxicity hazards that can be fatal or toxic. This is a high-concern symbol and should trigger careful review of exposure controls, PPE, first-aid information, and emergency procedures.' },
    { id: 'ghs-pictograms-p10', type: 'paragraph', text: 'The health hazard pictogram points to serious health hazards such as carcinogenicity, respiratory sensitization, reproductive toxicity, target organ toxicity, germ cell mutagenicity, or aspiration hazard depending on classification.' },
    { id: 'ghs-pictograms-p11', type: 'paragraph', text: 'The exclamation mark pictogram points to less severe but still important health effects, such as irritant, skin sensitizer, acute toxicity category 4, narcotic effects, or respiratory tract irritation depending on classification.' },
    { id: 'ghs-pictograms-p12', type: 'paragraph', text: 'The gas cylinder pictogram points to gases under pressure. Cylinders and pressurized containers can create physical hazards even when the chemical is not highly toxic or flammable. Storage, securing, temperature, and valve protection can matter.' },
    { id: 'ghs-pictograms-p13', type: 'paragraph', text: 'The environment pictogram points to aquatic toxicity in the broader GHS system. OSHA shows it for reference, but it is not mandatory under OSHA HazCom. Environmental and spill requirements may still come from other agencies, company policy, or the SDS.' },
    { id: 'ghs-pictograms-p14', type: 'paragraph', text: 'A chemical label can have more than one pictogram. Multiple pictograms mean multiple hazard types may apply. Do not pick only the symbol that seems most obvious; read the full label and SDS.' },
    { id: 'ghs-pictograms-p15', type: 'paragraph', text: 'GHS pictograms are not DOT placards or DOT package labels. Some symbols may look related to transportation hazards, but transportation compliance must be checked through the shipping paper, HMR classification, DOT labels, markings, placards, and identification-number display rules.' },
    { id: 'ghs-pictograms-p16', type: 'example', title: 'Example: flame pictogram', text: 'A workplace bottle has the GHS flame pictogram. That tells you to check flammability hazards, but it does not automatically mean the shipment requires Class 3 placards. For transport, check the shipping paper and HMR.' },
    { id: 'ghs-pictograms-p17', type: 'example', title: 'Example: corrosion pictogram', text: 'A chemical label shows corrosion. The chemical may damage skin, eyes, or metals depending on the hazard statement. Read the SDS before handling, and do not assume the DOT transport classification from the pictogram alone.' },
    { id: 'ghs-pictograms-p18', type: 'example', title: 'Example: two pictograms', text: 'A product has both flame and health hazard pictograms. That means workers should consider both fire-related hazards and serious health hazards. The SDS will explain the specific classifications and precautions.' },
    { id: 'ghs-pictograms-p19', type: 'checklist', title: 'Quick pictogram check', items: ['Identify every pictogram on the label.', 'Read the signal word: Danger or Warning.', 'Read the hazard statements that explain the pictograms.', 'Read the precautionary statements.', 'Open the SDS for handling, storage, PPE, first-aid, spill, and firefighting details.', 'Confirm workers understand the label system used at the site.', 'Do not use GHS pictograms alone to decide DOT labels, placards, or shipping papers.', 'Escalate unclear pictograms or unlabeled containers to a supervisor or safety contact.'] },
    { id: 'ghs-pictograms-p20', type: 'warning', title: 'Symbols are fast, but details keep people safe', text: 'Pictograms are designed for quick recognition, but quick recognition is not the same as full understanding. Use the pictogram as a prompt to read the label, SDS, and site procedure before handling the chemical.' }
  ],
  audioScript: 'GHS pictograms. GHS pictograms are red-diamond workplace chemical hazard symbols used under OSHA Hazard Communication. They help workers quickly recognize hazard types, but they do not replace the label text, Safety Data Sheet, training, or site procedures. OSHA requires eight pictograms under HazCom. The environmental pictogram exists in GHS but is not mandatory under OSHA. Common pictograms include flame, flame over circle, exploding bomb, corrosion, skull and crossbones, health hazard, exclamation mark, gas cylinder, and environment. A chemical can have more than one pictogram. GHS pictograms are not DOT placards or DOT package labels. For transportation decisions, check the shipping paper and HMR requirements.',
  tags: ['ghs pictograms', 'osha pictograms', 'hazcom pictograms', 'flame pictogram', 'corrosion pictogram', 'skull and crossbones', 'health hazard', 'exclamation mark', 'gas cylinder', 'flame over circle', 'exploding bomb', 'environment pictogram', 'sds'],
  sources: [
    { title: 'Hazard Communication Pictograms', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/pictograms', note: 'OSHA pictogram page explaining the red diamond format and pictogram meanings.' },
    { title: 'Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/', note: 'OSHA overview of HazCom, labels, SDSs, and training.' },
    { title: 'Hazard Communication Appendix C - Allocation of Label Elements', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/appendix-c', note: 'OSHA mandatory appendix covering label elements and pictogram allocation.' },
    { title: 'Hazard Communication Questions and Answers', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/faq', note: 'OSHA FAQ covering pictograms, workplace labels, and HazCom implementation questions.' },
    { title: 'BRIEF: Hazard Communication Standard: Labels and Pictograms', agency: 'OSHA', url: 'https://www.osha.gov/sites/default/files/publications/OSHA3636.pdf', note: 'OSHA brief explaining HazCom label elements and pictograms.' },
    { title: '29 CFR 1910.1200 - Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200', note: 'Official OSHA regulatory text for the Hazard Communication Standard.' }
  ],
  lastReviewed: '2026-05-20'
};
