import type { GuidePage } from '../types/content';

export const labelsMarkingsPlacardsPage: GuidePage = {
  id: 'labels-markings-placards',
  chapter: 14,
  title: 'DOT Labels, Markings, and Placards',
  category: 'hazmat-placards',
  summary: 'DOT labels, markings, and placards are different hazmat communication tools. Labels usually go on packages, markings provide required written or graphic information, and placards usually go on vehicles or transport units.',
  content: [
    { id: 'labels-markings-placards-p1', type: 'summary', title: 'The big difference', text: 'DOT hazmat labels, markings, and placards are related, but they are not the same thing. A label usually communicates package hazard class. A marking gives required information such as proper shipping name, identification number, orientation arrows, limited quantity marks, or other required text or symbols. A placard communicates hazard information on a vehicle, freight container, bulk package, or other transport unit when required.' },
    { id: 'labels-markings-placards-p2', type: 'warning', title: 'Do not treat one symbol as the whole answer', text: 'Seeing a Class 3 label, a UN number, a limited quantity mark, or a placard does not by itself answer every compliance question. The correct answer depends on the shipping paper, material classification, quantity, packaging, mode, exceptions, and the current HMR.' },
    { id: 'labels-markings-placards-p3', type: 'paragraph', text: 'Labels are generally placed on packages to show the hazard class or division of the hazardous material inside. Label requirements are mainly found in 49 CFR Part 172 Subpart E. Some materials require primary and subsidiary hazard labels depending on the Hazardous Materials Table and shipment details.' },
    { id: 'labels-markings-placards-p4', type: 'paragraph', text: 'Markings are required words, numbers, names, symbols, or other information placed on packages or bulk packages. Markings can include proper shipping names, UN or NA identification numbers, consignee or consignor information, orientation arrows, marine pollutant marks, limited quantity marks, or other required information depending on the shipment.' },
    { id: 'labels-markings-placards-p5', type: 'paragraph', text: 'Placards are larger hazard communication displays used on transport vehicles, freight containers, cargo tanks, portable tanks, bulk packages, or other transport units when required. Placarding requirements are mainly found in 49 CFR Part 172 Subpart F.' },
    { id: 'labels-markings-placards-p6', type: 'paragraph', text: 'Identification numbers are four-digit UN or NA numbers used to identify hazardous materials in transportation. They may appear on shipping papers, package markings, bulk package markings, orange panels, white square-on-point displays, or placards when the rules require them.' },
    { id: 'labels-markings-placards-p7', type: 'paragraph', text: 'A plain hazard class placard and a numbered display are not always interchangeable. Some situations may allow or require an identification number on a placard, orange panel, or white square-on-point display. Other shipments may need only the hazard class placard or may qualify for an exception.' },
    { id: 'labels-markings-placards-p8', type: 'paragraph', text: 'Bulk packaging often changes the marking and identification-number-display question. Bulk packages commonly have additional marking requirements compared with many non-bulk packages. Do not decide from the hazard class alone; check the packaging type and capacity.' },
    { id: 'labels-markings-placards-p9', type: 'paragraph', text: 'Placard tables matter. Under 49 CFR §172.504, some hazard classes are listed in Table 1 and generally require placarding for any quantity. Other hazard classes are in Table 2 and may depend on aggregate gross weight and other conditions. This is why the same-looking shipment can have a different placard answer depending on material and quantity.' },
    { id: 'labels-markings-placards-p10', type: 'paragraph', text: 'Visibility and condition matter. Labels, markings, and placards must be durable, visible, correctly placed, and not obscured in ways that defeat their hazard communication purpose. Damaged, covered, or mismatched hazard communication can create safety and enforcement problems.' },
    { id: 'labels-markings-placards-p11', type: 'paragraph', text: 'Old placards and marks can be misleading. If a vehicle, trailer, container, or package no longer contains the hazardous material that required the placard or mark, company procedures and regulations should be followed for removing, covering, or replacing incorrect hazard communication.' },
    { id: 'labels-markings-placards-p12', type: 'paragraph', text: 'GHS workplace labels are not DOT transport labels. A red GHS pictogram on a workplace chemical label can help communicate chemical hazards, but DOT hazmat transportation labels and placards are governed by the HMR and have their own requirements.' },
    { id: 'labels-markings-placards-p13', type: 'example', title: 'Example: package label vs vehicle placard', text: 'A box has a Class 3 flammable liquid label. That package label does not automatically prove the trailer needs Class 3 placards. The placard decision also depends on the shipping paper, quantity, packaging type, and the placarding tables and exceptions.' },
    { id: 'labels-markings-placards-p14', type: 'example', title: 'Example: UN number on a bulk package', text: 'A cargo tank may need the material identification number displayed, while a small non-bulk package of the same hazard class may use different package markings and labels. Bulk versus non-bulk changes the question.' },
    { id: 'labels-markings-placards-p15', type: 'example', title: 'Example: mismatch', text: 'If the shipping paper says UN1993 Flammable liquids, n.o.s., the package shows a different identification number, and the trailer has an unrelated placard, do not choose one at random. Stop and escalate to a trained hazmat/safety contact.' },
    { id: 'labels-markings-placards-p16', type: 'checklist', title: 'Quick labels/markings/placards check', items: ['Start with the shipping paper and material classification.', 'Confirm the proper shipping name, hazard class/division, identification number, and packing group when assigned.', 'Check package label requirements.', 'Check package marking requirements.', 'Check whether the shipment is bulk or non-bulk.', 'Check placarding requirements using the correct placard table and exceptions.', 'Check whether an identification number display is required.', 'Compare labels, markings, placards, and shipping papers for obvious mismatches.', 'Do not rely on GHS/SDS labels as DOT transport compliance.', 'Escalate uncertainty to a trained hazmat/safety contact.'] },
    { id: 'labels-markings-placards-p17', type: 'warning', title: 'Never “just give the easy placard” without checking', text: 'A driver may ask for a simple hazard class placard because an app, habit, or past load says it is enough. That can be wrong. Check the shipment details and current HMR before deciding whether numbered displays, specific placards, or exceptions apply.' }
  ],
  audioScript: 'DOT labels, markings, and placards. Labels, markings, and placards are related, but they are not the same thing. A label usually communicates hazard class on a package. A marking gives required information such as proper shipping name, identification number, orientation arrows, limited quantity marks, or other required symbols or words. A placard communicates hazard information on a vehicle, freight container, bulk package, or transport unit when required. The correct answer depends on the shipping paper, classification, quantity, packaging type, placarding tables, exceptions, and current HMR. GHS workplace labels are not DOT transport labels. If labels, markings, placards, and shipping papers do not match, stop and escalate to a trained hazmat or safety contact.',
  tags: ['dot labels', 'hazmat labels', 'markings', 'placards', 'identification number', 'un number', 'na number', 'orange panel', 'white square on point', 'placard table', 'table 1', 'table 2', 'bulk package', 'non bulk', 'ghs vs dot'],
  sources: [
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' },
    { title: '49 CFR Part 172 Subpart D - Marking', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172/subpart-D', note: 'Official eCFR regulatory text for hazmat marking requirements.' },
    { title: '49 CFR Part 172 Subpart E - Labeling', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172/subpart-E', note: 'Official eCFR regulatory text for hazmat labeling requirements.' },
    { title: '49 CFR Part 172 Subpart F - Placarding', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172/subpart-F', note: 'Official eCFR regulatory text for hazmat placarding requirements.' },
    { title: '49 CFR Section 172.504 - General placarding requirements', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/172504', note: 'PHMSA regulatory text page for general placarding requirements and placard tables.' },
    { title: 'Identifying Hazardous Materials in Your Community', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/standards-rulemaking/hazmat/identifying-hazardous-materials-in-your-community', note: 'PHMSA explanation of placards, colors, symbols, and identification numbers.' },
    { title: '49 CFR Part 172 - Hazardous Materials Table, Special Provisions, Communications, Emergency Response Information, Training Requirements, and Security Plans', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172', note: 'Official eCFR regulatory text for hazmat communication requirements.' }
  ],
  lastReviewed: '2026-05-20'
};
