import type { GuidePage } from '../types/content';

export const commonDockArgumentsPage: GuidePage = {
  id: 'common-dock-arguments',
  chapter: 18,
  title: 'Common Dock Arguments',
  category: 'common-situations',
  summary: 'Plain-English guidance for common dock disputes about placards, numbered displays, shipping papers, labels, SDS information, and who has authority to release a hazmat load.',
  content: [
    { id: 'common-dock-arguments-p1', type: 'summary', title: 'Why dock arguments happen', text: 'Dock arguments usually happen because people are looking at different pieces of the hazmat system. A driver may look at a placard app. A dock worker may look at a package label. A shipper may look at the shipping paper. A safety person may look at the HMR. The safest answer comes from lining those pieces up, not from whoever argues loudest.' },
    { id: 'common-dock-arguments-p2', type: 'warning', title: 'Do not release a questionable hazmat load by pressure', text: 'If the shipping paper, package labels, markings, placards, identification numbers, or driver instructions do not match, do not guess and do not release the load just because someone is in a hurry. Pause and escalate to a trained hazmat or safety contact.' },
    { id: 'common-dock-arguments-p3', type: 'paragraph', text: 'Argument: “The app says plain Class 3 placards are enough.” A driver’s app may be useful, but it is not the shipment record and it is not the regulation. Check the shipping paper, hazard class, identification number, quantity, packaging type, placarding table, and identification-number-display rules.' },
    { id: 'common-dock-arguments-p4', type: 'paragraph', text: 'Argument: “It has a label, so the truck needs placards.” A package label does not automatically answer the vehicle placard question. Labels usually apply to packages. Placards apply to transport vehicles, freight containers, bulk packages, or transport units when the placarding rules require them.' },
    { id: 'common-dock-arguments-p5', type: 'paragraph', text: 'Argument: “It is only one pallet, so no placards.” Quantity matters, but “one pallet” is not the rule. The answer depends on the material, hazard class, Table 1 or Table 2 status, aggregate gross weight, packaging, and exceptions.' },
    { id: 'common-dock-arguments-p6', type: 'paragraph', text: 'Argument: “It is in totes, so it is non-bulk.” Totes and IBCs can be bulk packaging depending on capacity and how the material is contained. Check the bulk packaging definition, capacity, and shipping paper before deciding marking or placarding requirements.' },
    { id: 'common-dock-arguments-p7', type: 'paragraph', text: 'Argument: “The SDS says flammable, so use flammable placards.” SDS information is not the same as the DOT shipping description. The DOT shipping paper and HMR classification drive transportation labels, markings, placards, and identification-number displays.' },
    { id: 'common-dock-arguments-p8', type: 'paragraph', text: 'Argument: “The trailer already has placards on it.” Old placards can be dangerous if they do not match the current load. A placard left on from a previous shipment can mislead emergency responders and enforcement. Confirm the current shipment before leaving placards in place.' },
    { id: 'common-dock-arguments-p9', type: 'paragraph', text: 'Argument: “The driver does not want numbered placards.” Preference does not control the rule. If the current shipment requires identification-number displays, the display must be correct. If a plain hazard class placard is allowed, that should also be verified from the shipment information and HMR.' },
    { id: 'common-dock-arguments-p10', type: 'paragraph', text: 'Argument: “The paperwork is wrong but the freight is right.” Mismatched paperwork and freight are a stop-and-escalate situation. Hazmat shipping papers communicate critical emergency response and enforcement information. Do not manually change the hazmat description unless trained, authorized, and following the applicable procedure.' },
    { id: 'common-dock-arguments-p11', type: 'paragraph', text: 'Argument: “It is empty, so take the placards off.” Empty or residue packaging can still be regulated depending on the material, packaging, and cleaning or purging status. Do not assume empty means unregulated.' },
    { id: 'common-dock-arguments-p12', type: 'paragraph', text: 'Argument: “This is how we always ship it.” Past practice is not proof. Rules can change, customers can change the material, concentration, package size, or quantity, and a different route or mode can change requirements.' },
    { id: 'common-dock-arguments-p13', type: 'paragraph', text: 'Argument: “I am the driver, so I decide.” Drivers have important responsibilities, but the offeror/shipper generally controls classification and shipping description preparation. Carriers and drivers must still check that required documents and hazard communication are present and usable. When there is a conflict, use the company safety escalation process.' },
    { id: 'common-dock-arguments-p14', type: 'example', title: 'Example: plain Class 3 dispute', text: 'A driver refuses numbered placards and asks for plain Class 3 placards. The safe response is to check the shipping paper, identify the UN/NA number, determine bulk versus non-bulk, check whether identification-number display is required, and escalate if the answer is unclear.' },
    { id: 'common-dock-arguments-p15', type: 'example', title: 'Example: package label confusion', text: 'A dock worker sees a Class 8 label on a small package and assumes the trailer must be placarded. The better process is to check the total quantity, Table 1/Table 2 status, packaging type, and exceptions before making the placard decision.' },
    { id: 'common-dock-arguments-p16', type: 'example', title: 'Example: old placards', text: 'A trailer arrives with flammable placards already installed, but the current shipment is non-hazmat. The old placards can miscommunicate the current load. Follow company procedure to remove, cover, or correct hazard communication before release.' },
    { id: 'common-dock-arguments-p17', type: 'checklist', title: 'Dock dispute checklist', items: ['Stop the argument and identify the exact question.', 'Start with the shipping paper, not memory or habit.', 'Confirm proper shipping name, identification number, hazard class/division, and packing group when assigned.', 'Check package labels and markings against the paperwork.', 'Check bulk versus non-bulk packaging.', 'Check placarding and identification-number-display rules.', 'Check whether any exception truly applies.', 'Do not rely on SDS/GHS as DOT placarding authority.', 'Escalate mismatches to a trained hazmat/safety contact.', 'Document the issue if company procedure requires it.'] },
    { id: 'common-dock-arguments-p18', type: 'warning', title: 'The goal is not winning the argument', text: 'The goal is a safe, legal, correctly communicated shipment. If the documents, freight, placards, or instructions do not agree, the right move is to pause and verify.' }
  ],
  audioScript: 'Common dock arguments. Dock disputes happen when people look at different parts of the hazmat system. A driver may look at an app. A dock worker may look at a package label. A shipper may look at the shipping paper. A safety person may look at the HMR. The safest answer comes from lining those pieces up. A driver saying plain Class 3 placards are enough is not the final answer. A package label does not automatically mean vehicle placards are required. An SDS does not replace the DOT shipping description. Old placards can be misleading. Empty or residue packages can still matter. When paperwork, labels, markings, placards, or identification numbers do not match, pause the load and escalate to a trained hazmat or safety contact.',
  tags: ['dock arguments', 'driver dispute', 'placard dispute', 'plain class 3 placard', 'numbered placards', 'shipping papers', 'sds vs dot', 'old placards', 'empty packaging', 'residue', 'hazmat mismatch'],
  sources: [
    { title: '49 CFR Part 172 - Hazardous Materials Table, Special Provisions, Communications, Emergency Response Information, Training Requirements, and Security Plans', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172', note: 'Official eCFR text covering hazmat communication requirements.' },
    { title: '49 CFR Section 172.202 - Description of hazardous material on shipping papers', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/172202', note: 'PHMSA regulatory text page for hazardous material descriptions on shipping papers.' },
    { title: '49 CFR Section 172.504 - General placarding requirements', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulations/title49/section/172504', note: 'PHMSA regulatory text page for general placarding requirements and placard tables.' },
    { title: '49 CFR Section 171.8 - Definitions and abbreviations', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-171.8', note: 'Official eCFR definitions including bulk packaging.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' },
    { title: 'Hazardous Materials: Emergency Response Information Requirements', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/regulatory-compliance/phmsa-guidance/hazardous-materials-emergency-response-information', note: 'PHMSA guidance about emergency response information related to shipping papers and hazardous materials.' }
  ],
  lastReviewed: '2026-05-20'
};
