import type { GuidePage } from '../types/content';

export const scenarioExamplesPage: GuidePage = {
  id: 'scenario-examples',
  chapter: 24,
  title: 'Scenario Examples',
  category: 'common-situations',
  summary: 'Real-world style examples that show how to slow down and apply the right rule set for HOS, ELD, hazmat, placards, GHS labels, and SDS questions.',
  content: [
    { id: 'scenario-examples-p1', type: 'summary', title: 'How to use scenarios', text: 'These scenarios are practice-style guidance. They show how to think through common problems, but they do not certify a shipment, approve a driver to operate, replace an ELD, replace hazmat training, or override company safety procedures.' },
    { id: 'scenario-examples-p2', type: 'warning', title: 'Scenarios are not exceptions', text: 'A scenario is not a rule exception by itself. If the driver, dock worker, shipper, carrier, or employer cannot name the exact rule and confirm the exact facts, pause and verify before acting.' },
    { id: 'scenario-examples-p3', type: 'example', title: 'Scenario 1: Driver has 11-hour time but no cycle time', text: 'A property-carrying driver says the ELD shows several daily driving hours left, but the cycle clock is nearly zero. The correct question is not only the 11-hour driving limit. Check the 60/70-hour cycle. If the driver is out of cycle hours, driving may not be allowed even if daily driving time remains.' },
    { id: 'scenario-examples-p4', type: 'example', title: 'Scenario 2: Driver wants to use adverse driving conditions', text: 'A driver was delayed by normal rush-hour traffic and wants extra time under adverse driving conditions. Normal predictable traffic is not the same as an unexpected adverse driving condition. Verify whether the condition was unexpected, could not reasonably have been known before dispatch, and meets the official rule.' },
    { id: 'scenario-examples-p5', type: 'example', title: 'Scenario 3: 30-minute break misunderstanding', text: 'A driver says a 30-minute break resets the day. That is wrong. The 30-minute break rule is an interruption after cumulative driving time. It does not reset the 11-hour driving limit, does not restart the 14-hour window, and does not restart the 60/70-hour cycle.' },
    { id: 'scenario-examples-p6', type: 'example', title: 'Scenario 4: Split sleeper guess', text: 'A driver says 6 hours in the sleeper berth plus 4 hours off duty should count as a split. Under the normal property-carrying split sleeper rule, one qualifying period generally needs at least 7 consecutive hours in the sleeper berth, and the paired periods need to total at least 10 hours. Verify the actual log and rule before relying on a split.' },
    { id: 'scenario-examples-p7', type: 'example', title: 'Scenario 5: ELD malfunction', text: 'The ELD cannot display or transfer the driver’s records. The driver should follow the ELD malfunction instructions, use backup records when required, notify the carrier according to policy and regulation, and avoid treating the malfunction as permission to ignore HOS.' },
    { id: 'scenario-examples-p8', type: 'example', title: 'Scenario 6: Driver refuses numbered placards', text: 'A driver refuses numbered placards and asks for plain Class 3 placards. Do not argue from habit. Check the shipping paper, UN or NA number, hazard class, quantity, bulk versus non-bulk packaging, placarding table, and identification-number-display requirements. Escalate if the answer is unclear.' },
    { id: 'scenario-examples-p9', type: 'example', title: 'Scenario 7: Class label on one package', text: 'A dock worker sees a Class 8 label on one package and assumes the whole trailer needs placards. A package label does not automatically decide vehicle placards. Check Table 1/Table 2 logic, aggregate gross weight, other hazmat on the vehicle, package type, and exceptions.' },
    { id: 'scenario-examples-p10', type: 'example', title: 'Scenario 8: 275-gallon tote', text: 'A 275-gallon tote of regulated liquid is loaded for shipment. Because it is above the common 119-gallon liquid bulk threshold, bulk packaging requirements likely apply if the material is loaded with no intermediate form of containment and no exception applies. Check bulk package markings, placards, and identification-number-display requirements before release.' },
    { id: 'scenario-examples-p11', type: 'example', title: 'Scenario 9: Old placards on trailer', text: 'A trailer arrives with old flammable placards from a previous load. If the current shipment does not match those placards, the placards can mislead emergency responders and enforcement. Follow company procedure to remove, cover, or correct incorrect hazard communication.' },
    { id: 'scenario-examples-p12', type: 'example', title: 'Scenario 10: Shipping paper mismatch', text: 'The shipping paper shows one UN number, the package marking shows another, and the driver requests a different placard. This is a stop-and-escalate situation. Do not pick whichever answer seems easiest. A trained hazmat/safety contact needs to resolve the mismatch before the shipment moves.' },
    { id: 'scenario-examples-p13', type: 'example', title: 'Scenario 11: SDS says flammable', text: 'An SDS says a product has flammability hazards, and someone wants Class 3 placards based only on the SDS. The SDS supports safety awareness, but DOT transportation decisions must be checked against the shipping paper, current classification, packaging, quantity, and HMR placarding rules.' },
    { id: 'scenario-examples-p14', type: 'example', title: 'Scenario 12: GHS flame pictogram', text: 'A workplace container has a GHS flame pictogram. That helps workers recognize a flammability-related hazard. It does not automatically decide DOT shipping papers, package labels, placards, or identification-number displays.' },
    { id: 'scenario-examples-p15', type: 'example', title: 'Scenario 13: Missing SDS', text: 'A worker needs PPE information, but the SDS is missing or unavailable. Do not guess from memory. Use the employer SDS system, supervisor, or safety contact to get the correct SDS before handling the chemical.' },
    { id: 'scenario-examples-p16', type: 'example', title: 'Scenario 14: Empty bulk package', text: 'A bulk package is called empty, but it may still contain residue. Empty or residue packaging can still have hazmat requirements unless an exception, cleaning, purging, or other rule applies. Do not remove hazard communication or release the package by assumption.' },
    { id: 'scenario-examples-p17', type: 'example', title: 'Scenario 15: Short-haul assumption', text: 'A local driver says short-haul means no logs and no rules. Short-haul can change normal recordkeeping and the 30-minute break requirement only when all conditions are met. Time records, radius, return-to-location, and duty-period conditions still matter.' },
    { id: 'scenario-examples-p18', type: 'checklist', title: 'Scenario response pattern', items: ['Name the exact question first.', 'Decide whether the question is HOS, ELD, DOT hazmat, GHS/HazCom, SDS, or company procedure.', 'Start with the controlling document: ELD/log, shipping paper, container label, SDS, or official rule.', 'Check facts, not memory.', 'Compare documents and physical labels/markings/displays for mismatches.', 'Do not invent an exception.', 'Escalate when facts conflict or the user is not trained/authorized to decide.'] },
    { id: 'scenario-examples-p19', type: 'warning', title: 'When pressure goes up, slow down', text: 'Many mistakes happen because a driver is waiting, a dock is busy, or someone wants the fastest answer. High pressure is a reason to slow down, compare the documents, and escalate — not a reason to guess.' }
  ],
  audioScript: 'Scenario examples. These scenarios show how to slow down and apply the right rule set. For HOS, use the actual ELD or log and check each clock separately. For ELD problems, follow malfunction, transfer, and record procedures. For hazmat, start with the shipping paper, then check labels, markings, placards, packaging, quantity, and identification-number displays. For GHS and SDS questions, use the workplace label, SDS, training, and employer procedure. Do not use a scenario as an exception. If facts conflict, pause and escalate to a trained supervisor or safety contact.',
  tags: ['scenario examples', 'hos scenarios', 'eld scenario', 'placard dispute', 'numbered placards', 'shipping paper mismatch', 'ghs scenario', 'sds scenario', 'dock scenario', 'hazmat examples'],
  sources: [
    { title: 'Summary of Hours of Service Regulations', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/summary-hours-service-regulations', note: 'FMCSA HOS summary used for HOS scenario logic.' },
    { title: 'Electronic Logging Devices', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/electronic-logging-devices', note: 'FMCSA ELD overview used for ELD scenario logic.' },
    { title: '49 CFR Part 172 - Hazardous Materials Table, Special Provisions, Communications, Emergency Response Information, Training Requirements, and Security Plans', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172', note: 'Official eCFR hazmat communication rules used for shipping paper, label, marking, placard, and identification-number scenarios.' },
    { title: '49 CFR Section 171.8 - Definitions and abbreviations', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/section-171.8', note: 'Official eCFR definitions used for bulk packaging and residue-related scenario cautions.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' },
    { title: 'Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/', note: 'OSHA HazCom overview used for GHS and SDS scenario logic.' }
  ],
  lastReviewed: '2026-05-20'
};
