import type { GuidePage } from '../types/content';

export const ghsVsDotPage: GuidePage = {
  id: 'ghs-vs-dot',
  chapter: 22,
  title: 'GHS vs DOT',
  category: 'ghs-sds',
  summary: 'GHS/HazCom and DOT hazmat both communicate chemical hazards, but they answer different questions. GHS supports workplace safety; DOT HMR controls transportation classification, shipping papers, labels, markings, placards, and identification-number displays.',
  content: [
    { id: 'ghs-vs-dot-p1', type: 'summary', title: 'The simple difference', text: 'GHS/HazCom is mainly about workplace chemical hazard communication. DOT hazmat rules are about transportation of hazardous materials in commerce. They overlap in real life, but they are not interchangeable.' },
    { id: 'ghs-vs-dot-p2', type: 'warning', title: 'Do not use one system to replace the other', text: 'A GHS pictogram does not decide DOT placards. A DOT placard does not replace an SDS. A shipping paper does not replace workplace HazCom training. Use the right system for the question being asked.' },
    { id: 'ghs-vs-dot-p3', type: 'paragraph', text: 'OSHA’s Hazard Communication Standard requires chemical hazard information to be communicated to workers through labels, Safety Data Sheets, and training. It focuses on workplace exposure, handling, storage, emergency actions, and employee understanding.' },
    { id: 'ghs-vs-dot-p4', type: 'paragraph', text: 'DOT hazardous materials regulations focus on safe transportation. They cover classification, shipping papers, package marking and labeling, placarding, emergency response information, packaging, training, and transportation-specific requirements.' },
    { id: 'ghs-vs-dot-p5', type: 'paragraph', text: 'GHS labels use elements such as product identifier, signal word, hazard statements, pictograms, precautionary statements, and supplier information. DOT transportation communication uses elements such as proper shipping name, identification number, hazard class or division, packing group when assigned, package labels, markings, placards, and shipping papers.' },
    { id: 'ghs-vs-dot-p6', type: 'paragraph', text: 'Some symbols may look similar or point to related hazards, but they serve different legal purposes. A GHS flame pictogram warns workers about flammability-related hazards. A DOT Class 3 label or placard communicates a transportation hazard class under the HMR.' },
    { id: 'ghs-vs-dot-p7', type: 'paragraph', text: 'The SDS can support DOT awareness, especially Section 14 transport information, but it should not be treated as the final transportation document for a specific shipment. The active shipping paper, current classification, quantity, packaging, and HMR requirements must be checked.' },
    { id: 'ghs-vs-dot-p8', type: 'paragraph', text: 'OSHA HazCom labels are usually found on chemical containers in workplaces or on shipped chemical containers for workplace hazard communication. DOT labels and placards are used for transportation hazard communication and are governed by 49 CFR hazmat rules.' },
    { id: 'ghs-vs-dot-p9', type: 'paragraph', text: 'A chemical can have both workplace and transportation hazards. For example, a chemical can need HazCom workplace labeling and SDS access while also needing DOT shipping papers, package labels, markings, placards, or identification-number displays when transported.' },
    { id: 'ghs-vs-dot-p10', type: 'paragraph', text: 'Employer procedures matter. A site may require workers to check both the SDS and the shipping paper before a load moves. That is not duplication; it is checking two different systems that answer different safety questions.' },
    { id: 'ghs-vs-dot-p11', type: 'paragraph', text: 'Training requirements also differ. OSHA HazCom training teaches workers about workplace chemical hazards, label systems, SDSs, and protective measures. DOT hazmat training covers transportation-specific functions such as classification, packaging, shipping papers, marking, labeling, placarding, security awareness, and function-specific duties.' },
    { id: 'ghs-vs-dot-p12', type: 'paragraph', text: 'If a GHS label, SDS, DOT label, shipping paper, package marking, placard, or identification-number display appears to conflict, do not guess which one is right. Pause and escalate to a trained supervisor, hazmat/safety contact, or the person responsible for the shipment.' },
    { id: 'ghs-vs-dot-p13', type: 'example', title: 'Example: flame pictogram vs Class 3 placard', text: 'A bottle has a GHS flame pictogram. That warns workers about flammability-related hazards. It does not automatically mean the truck needs Class 3 placards. For transportation, check the shipping paper, quantity, packaging, and placarding rules.' },
    { id: 'ghs-vs-dot-p14', type: 'example', title: 'Example: SDS Section 14', text: 'SDS Section 14 lists transport information, but the shipping paper for the actual shipment may be more specific. Before a load moves, verify the current shipping description, package type, quantity, and DOT requirements.' },
    { id: 'ghs-vs-dot-p15', type: 'example', title: 'Example: workplace bottle vs outbound freight', text: 'A workplace bottle may need a HazCom label for employee safety. An outbound pallet or bulk package may also need DOT package labels, markings, placards, or identification-number displays. One label system does not automatically satisfy the other.' },
    { id: 'ghs-vs-dot-p16', type: 'checklist', title: 'Quick GHS vs DOT check', items: ['Ask: is this a workplace safety question or a transportation compliance question?', 'For workplace safety, check the HazCom label, SDS, training, PPE, storage, and employer procedure.', 'For transportation, check the shipping paper, proper shipping name, identification number, hazard class/division, packing group when assigned, quantity, and packaging.', 'Do not use GHS pictograms alone to decide DOT placards.', 'Do not use DOT placards as a replacement for SDS access or HazCom training.', 'Check SDS Section 14 only as support, not as the sole transport authority.', 'Escalate conflicts between SDS, labels, markings, placards, and shipping papers.'] },
    { id: 'ghs-vs-dot-p17', type: 'warning', title: 'Use the right rulebook', text: 'For workplace chemical communication, use OSHA HazCom and employer procedures. For transportation hazmat compliance, use PHMSA/DOT HMR and the actual shipment documents. Mixing the two systems can create wrong answers.' }
  ],
  audioScript: 'GHS versus DOT. GHS and OSHA HazCom are mainly about workplace chemical hazard communication. DOT hazmat rules are about transportation of hazardous materials in commerce. GHS labels use product identifiers, signal words, hazard statements, pictograms, precautionary statements, and supplier information. DOT transportation communication uses proper shipping names, identification numbers, hazard classes or divisions, packing groups when assigned, package labels, markings, placards, and shipping papers. A GHS pictogram does not decide DOT placards. A DOT placard does not replace an SDS. SDS Section 14 can support transport awareness, but the active shipping paper and current HMR requirements must be checked before a shipment moves.',
  tags: ['ghs vs dot', 'hazcom vs hazmat', 'osha hazcom', 'dot hazmat', 'sds section 14', 'ghs pictogram', 'dot placard', 'shipping paper', 'workplace label', 'transportation label'],
  sources: [
    { title: 'Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/', note: 'OSHA overview of HazCom labels, SDSs, and training.' },
    { title: 'Globally Harmonized System', agency: 'OSHA', url: 'https://www.osha.gov/hazcom/global', note: 'OSHA explanation of GHS as an international approach to chemical hazard communication.' },
    { title: '29 CFR 1910.1200 - Hazard Communication', agency: 'OSHA', url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200', note: 'Official OSHA regulatory text for the Hazard Communication Standard.' },
    { title: 'Hazardous Materials Regulations', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/standards-rulemaking/hazmat/hazardous-materials-regulations', note: 'PHMSA overview of the Hazardous Materials Regulations.' },
    { title: '49 CFR Part 172 - Hazardous Materials Table, Special Provisions, Communications, Emergency Response Information, Training Requirements, and Security Plans', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-172', note: 'Official eCFR regulatory text for DOT hazmat communication requirements.' },
    { title: 'DOT Chart 16 - Hazardous Materials Markings, Labeling and Placarding Guide', agency: 'PHMSA', url: 'https://www.phmsa.dot.gov/training/hazmat/dot-chart-16-hazardous-materials-markings-labeling-and-placarding-guide', note: 'Official PHMSA general guidance chart. Verify actual compliance against current 49 CFR hazardous materials regulations.' }
  ],
  lastReviewed: '2026-05-20'
};
