import type { GuidePage } from '../types/content';

export const eldBasicsPage: GuidePage = {
  id: 'eld-basics',
  chapter: 11,
  title: 'ELD Basics',
  category: 'hos',
  summary: 'An ELD records HOS duty-status data for drivers who are required to keep records of duty status, but it does not change the HOS rules or replace driver responsibility.',
  content: [
    { id: 'eld-basics-p1', type: 'summary', title: 'What an ELD does', text: 'An electronic logging device, or ELD, connects with the vehicle engine and automatically records driving time for hours-of-service recordkeeping. It is used to help track, manage, and share records of duty status.' },
    { id: 'eld-basics-p2', type: 'warning', title: 'An ELD is not the rule itself', text: 'FMCSA says the ELD final rule does not change the basic hours-of-service rules or exceptions. The device records and displays information, but the driver and carrier still have to understand the HOS rules, exceptions, duty status choices, and company procedures.' },
    { id: 'eld-basics-p3', type: 'paragraph', text: 'The ELD requirement generally applies to commercial drivers who are required to prepare HOS records of duty status. Some drivers and operations may be excepted from ELD use or from normal records of duty status, such as certain short-haul drivers when all conditions are met.' },
    { id: 'eld-basics-p4', type: 'paragraph', text: 'An ELD automatically records certain information such as date, time, location information, engine hours, vehicle miles, and identification information for the driver, authenticated user, vehicle, and motor carrier. Location is recorded at specific events and intervals, not as a simple replacement for understanding HOS status.' },
    { id: 'eld-basics-p5', type: 'paragraph', text: 'A driver still has to choose and manage the correct duty status when the device requires driver input. On duty not driving, off duty, sleeper berth, personal conveyance, and yard moves can have different HOS consequences. A wrong status can create a false picture of available time.' },
    { id: 'eld-basics-p6', type: 'paragraph', text: 'Automatically recorded driving time cannot simply be edited into non-driving time because the driver wants more hours. FMCSA guidance allows edits and annotations in certain situations, but automatically recorded driving time has strict handling rules and edits must preserve the record.' },
    { id: 'eld-basics-p7', type: 'paragraph', text: 'During a roadside inspection, the driver must be able to show or transfer HOS information as required. FMCSA materials explain that a driver must be able to provide either the display or a printout when an authorized safety official requests a physical display of the information.' },
    { id: 'eld-basics-p8', type: 'paragraph', text: 'Required ELD information should be available in the vehicle, including a user manual, instructions for transferring HOS records to safety officials, malfunction instruction materials, and a supply of blank records of duty status graph-grids for at least 8 days in case of ELD malfunction.' },
    { id: 'eld-basics-p9', type: 'paragraph', text: 'If the ELD malfunctions and cannot accurately record or present HOS data, the driver may need to use paper logs or another allowed system during the malfunction period, follow the ELD malfunction instructions, and provide reconstructed records when required.' },
    { id: 'eld-basics-p10', type: 'paragraph', text: 'Unidentified driving records matter. ELD systems can create unidentified driver records when the vehicle moves without a logged-in driver or when records are not assigned correctly. Drivers and carriers should review, accept, reject, or annotate records according to their system and FMCSA requirements.' },
    { id: 'eld-basics-p11', type: 'paragraph', text: 'ELD data can also raise harassment and coercion concerns if a carrier uses connected technology to pressure a driver to violate HOS rules or drive while ill or fatigued. FMCSA materials describe driver protections against harassment and coercion.' },
    { id: 'eld-basics-p12', type: 'paragraph', text: 'This app is not an ELD. It does not record duty status, connect to the engine, transfer official HOS files, certify logs, calculate legal availability, or replace the driver’s ELD, paper log, carrier system, or official records.' },
    { id: 'eld-basics-p13', type: 'example', title: 'Example: device says time is available', text: 'An ELD screen may show remaining time, but the driver still has to know whether an exception was used correctly, whether records are assigned correctly, and whether company policy or state rules are stricter.' },
    { id: 'eld-basics-p14', type: 'example', title: 'Example: short-haul driver', text: 'A driver who truly qualifies for a short-haul timecard exception may not need to use an ELD for that operation. If the driver stops qualifying, normal recordkeeping or ELD requirements may apply again.' },
    { id: 'eld-basics-p15', type: 'example', title: 'Example: malfunction', text: 'If the ELD has a malfunction that prevents accurate HOS recording or presentation, the driver should follow the device malfunction instructions, use required backup records when needed, and notify the carrier as required by policy and regulation.' },
    { id: 'eld-basics-p16', type: 'checklist', title: 'Quick ELD check', items: ['Confirm whether the driver is required to use an ELD for this operation.', 'Confirm the driver is logged in before driving when required.', 'Confirm duty status choices are correct.', 'Review unidentified driving records and annotations.', 'Know how to display or transfer records during inspection.', 'Keep required ELD user documents and backup graph-grids available.', 'Follow malfunction procedures if the device fails.', 'Do not treat the ELD as permission to violate HOS rules.'] },
    { id: 'eld-basics-p17', type: 'warning', title: 'Do not use this app as a logbook', text: 'Driver Rulebook can explain ELD concepts, but it cannot create compliant HOS records. Use the official ELD, carrier system, paper logs when allowed or required, and qualified safety guidance.' }
  ],
  audioScript: 'ELD basics. An electronic logging device connects with the vehicle engine and automatically records driving time for hours-of-service recordkeeping. It helps track, manage, and share records of duty status, but it does not change the basic HOS rules or exceptions. Drivers still have to choose correct duty statuses, handle edits and annotations correctly, manage unidentified driving records, and know how to display or transfer records during inspection. Required ELD documents and backup graph-grids should be available in the vehicle. If the ELD malfunctions, follow malfunction procedures and use backup records when required. Driver Rulebook is not an ELD or logbook.',
  tags: ['eld', 'electronic logging device', 'records of duty status', 'rods', 'hos', 'roadside inspection', 'data transfer', 'malfunction', 'unidentified driving', 'paper logs', 'short haul'],
  sources: [
    { title: 'Electronic Logging Devices', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/electronic-logging-devices', note: 'FMCSA ELD overview explaining automatic driving-time recording and that ELDs do not change basic HOS rules or exceptions.' },
    { title: 'ELD FAQ1: Key requirements of the ELD rule', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/eld-faq1-electronic-logging-devices-and-hours-service', note: 'FMCSA FAQ stating the ELD rule requires ELD use by commercial drivers required to prepare HOS records of duty status.' },
    { title: 'What ELD user documentation must be onboard?', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/what-electronic-logging-device-eld-user-documentation-must-be-onboard-drivers', note: 'FMCSA guidance listing required onboard ELD user documentation and backup graph-grids.' },
    { title: 'ELD Functions', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/eld-functions', note: 'FMCSA explanation of ELD data elements and recording events.' },
    { title: 'ELD Data Transfer', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/eld-data-transfer', note: 'FMCSA explanation of roadside display, printout, and transfer expectations.' },
    { title: 'ELD Malfunctions and Data Diagnostic Events FAQs', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/regulations/hours-service/elds/eld-malfunctions-and-data-diagnostic-events-faqs', note: 'FMCSA guidance for malfunction and diagnostic events.' },
    { title: 'ELD Checklist for Drivers', agency: 'FMCSA', url: 'https://www.fmcsa.dot.gov/hours-service/elds/eld-checklist-drivers', note: 'FMCSA checklist covering driver preparation, transfer, malfunction, paper tracking forms, harassment, and coercion.' },
    { title: '49 CFR Part 395 - Hours of Service of Drivers', agency: 'eCFR', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-395', note: 'Official eCFR regulatory text for HOS and ELD requirements.' }
  ],
  lastReviewed: '2026-05-20'
};
